/* [Remove/modify this line not to overwrite this file] */
/* Generated by RPARSE 2026-06-08 03:56 */

/* Reactions:
     S > beta*S*I/vol > E
     E > sigmaE*E > I
     I > gammaI*I > R
*/

#include <math.h>
#include "propensities.h"
#include "report.h"

enum Species {
  S,
  E,
  I,
  R
};

const int NR = 3; /* number of reactions */

/* rate constants */
enum gdataRATE {
  sigmaE,
  gammaI
};

enum ldata_timeRATE {
  beta
};

/* forward declarations */
double rFun1(const URDMEstate_t *xstate,double time,double vol,
             const double *ldata,const double *gdata,
             const double *ldata_time,const double *gdata_time,int sd);
double rFun2(const URDMEstate_t *xstate,double time,double vol,
             const double *ldata,const double *gdata,
             const double *ldata_time,const double *gdata_time,int sd);
double rFun3(const URDMEstate_t *xstate,double time,double vol,
             const double *ldata,const double *gdata,
             const double *ldata_time,const double *gdata_time,int sd);

/* static propensity vector */
static PropensityFun ptr[] = {rFun1,rFun2,rFun3};

/* propensity definitions */
double rFun1(const URDMEstate_t *xstate,double time,double vol,
             const double *ldata,const double *gdata,
             const double *ldata_time,const double *gdata_time,int sd)
{
  return ldata_time[beta]*xstate[S]*xstate[I]/vol;
}

double rFun2(const URDMEstate_t *xstate,double time,double vol,
             const double *ldata,const double *gdata,
             const double *ldata_time,const double *gdata_time,int sd)
{
  return gdata[sigmaE]*xstate[E];
}

double rFun3(const URDMEstate_t *xstate,double time,double vol,
             const double *ldata,const double *gdata,
             const double *ldata_time,const double *gdata_time,int sd)
{
  return gdata[gammaI]*xstate[I];
}

/* URDME solver interface */
PropensityFun *ALLOC_propensities(size_t Mreactions)
{
  if (Mreactions > NR) PERROR("Wrong number of reactions.");
  return ptr;
}

void FREE_propensities(PropensityFun *ptr)
{ /* do nothing since a static array was used */ }

