%STARTUP Initialize environment for the hybrid epidemic forecasting project.
%
%   Description:
%       Explicitly adds script, configuration, and nested source folders to
%       the MATLAB path. External dependencies such as URDME and StenLib are
%       expected to be available from the user's MATLAB environment. The
%       script also initializes the required directory structure for data and
%       results artifacts.
%
%   Workflow:
%       1. Add project configuration, script, and source folders to the path.
%       2. Create the data and result directories required by the pipelines.
%
%   See also PARTA_01_GENERATE_TRUTH, PARTB_01_GENERATE_ROBUSTNESS_DATASETS,
%            PARTC_01_PREPARE_DATA.
%
% A. M. Kaahin 2026-02-18
% Modified: 2026-08-23

%% 1. Path Management
repo_root = fileparts(mfilename('fullpath'));

addpath(fullfile(repo_root, 'config'));
addpath(genpath(fullfile(repo_root, 'scripts')));
addpath(genpath(fullfile(repo_root, 'src')));

%% 2. Directory Initialization
required_dirs = {
    'data/partA', ...
    'data/partB', ...
    'data/partC', ...
    'data/partC/raw', ...
    'data/partC/prepared', ...
    'results/partA/figures', ...
    'results/partA/forecasts', ...
    'results/partA/model_selection', ...
    'results/partA/evaluation', ...
    'results/partA/tables', ...
    'results/partA/logs', ...
    'results/partB/figures', ...
    'results/partB/evaluation', ...
    'results/partB/forecasts', ...
    'results/partB/tables', ...
    'results/partB/logs', ...
    'results/partC/figures', ...
    'results/partC/forecasts', ...
    'results/partC/evaluation', ...
    'results/partC/tables', ...
    'results/partC/logs'
    };

for i = 1:length(required_dirs)
    required_path = fullfile(repo_root, required_dirs{i});
    if ~exist(required_path, 'dir')
        mkdir(required_path);
    end
end
