%STARTUP Initialize environment for the hybrid epidemic forecasting project.
%
%   Description:
%       Explicitly adds script, configuration, and nested
%       source folders to the MATLAB path. Also initializes the required
%       directory structure for data and results artifacts.

% A. M. Kaahin 2026-02-18

%% 1. Path Management
addpath(fullfile(pwd, 'config'));
addpath(genpath(fullfile(pwd, 'scripts')));
addpath(genpath(fullfile(pwd, 'src')));

%% 2. Directory Initialization
required_dirs = {'data/partA', ...
                 'data/partB', ...
                 'data/partC', ...
                 'data/partC/raw', ...
                 'data/partC/processed', ...
                 'results/partA/figures', ...
                 'results/partA/forecasts', ...
                 'results/partA/scores', ...
                 'results/partA/tuning', ...
                 'results/partA/logs', ...
                 'results/partB/figures', ...
                 'results/partB/forecasts', ...
                 'results/partB/scores', ...
                 'results/partB/logs', ...
                 'results/partC/figures', ...
                 'results/partC/forecasts', ...
                 'results/partC/scores', ...
                 'results/partC/logs'};

for i = 1:length(required_dirs)
    if ~exist(required_dirs{i}, 'dir')
        mkdir(required_dirs{i});
    end
end
