function cfg = partC_config()
%PARTC_CONFIG Configure Part C observed-incidence adaptation.
%
%   Description:
%       Defines the WHO source schema, Swedish study period, renewal-estimator
%       assumptions, reported-case SIRS state-reconstruction assumptions,
%       chronological validation split, limited local configuration selection
%       protocol, compatibility snapshots, and canonical Part C artifact paths.
%
%   Outputs:
%       cfg - Structure containing:
%           .source      : WHO source file and exact input columns.
%           .country     : Selected country name and code.
%           .study       : Inclusive study-period endpoints.
%           .renewal     : Serial-interval and infectiousness assumptions.
%           .preparation : Approved incidence preprocessing method.
%           .state_reconstruction : Reported-case SIRS proxy assumptions.
%           .validation  : Fixed calibration and test boundary dates.
%           .local_selection : Shared settings and supported configurations.
%           .snapshot    : Stable Part C compatibility snapshots.
%           .output      : Canonical prepared-data and selection paths.
%
%   See also PARTC_01_PREPARE_DATA, PARTC_02_SELECT_LOCAL_ORDERS, ...
%            PARTA_CONFIG, SERIAL_INTERVAL_WEIGHTS, ...
%            RECONSTRUCT_SIRS_STATES_FROM_INCIDENCE.
%
% A. M. Kaahin 2026-07-27
% Modified: 2026-08-06

cfg = struct();
partA_cfg = partA_config();

%% 1. WHO Source
thisDir = fileparts(mfilename('fullpath'));
repoRoot = fileparts(thisDir);

cfg.source.file = fullfile(repoRoot, "data", "partC", "raw", ...
    "WHO-COVID-19-global-daily-data.csv");
cfg.source.columns = struct( ...
    "date", "Date_reported", ...
    "country_code", "Country_code", ...
    "country", "Country", ...
    "incidence", "New_cases");

cfg.country.name = "Sweden";
cfg.country.code = "SE";

%% 2. Study Period
cfg.study.start_date = datetime(2020, 3, 3);
cfg.study.end_date   = datetime(2021, 6, 14);

%% 3. Renewal Assumptions
% Nishiura, Linton, and Akhmetzhanov (2020), "Serial interval of
% novel coronavirus (COVID-19) infections", International Journal of
% Infectious Diseases 93:284-286, doi:10.1016/j.ijid.2020.02.060,
% estimated an early-COVID serial-interval mean of 4.7 days and standard
% deviation of 2.9 days from 28 transmission pairs. Part C uses those moments
% as a gamma approximation for this renewal estimator; they are not a general
% project convention or universally fixed biological truth. The 21-day lag is
% a numerical truncation of the positive distribution.
cfg.renewal.serial_interval_mean_days = 4.7;
cfg.renewal.serial_interval_sd_days = 2.9;
cfg.renewal.serial_interval_max_lag_days = 21;
cfg.renewal.min_infectiousness = 0;
cfg.renewal.serial_interval_source = ...
    "Nishiura H, Linton NM, Akhmetzhanov AR (2020), International Journal of Infectious Diseases 93:284-286, doi:10.1016/j.ijid.2020.02.060.";

%% 4. Incidence Preparation
cfg.preparation.incidence_preprocessing = "none";

%% 5. Reported-Case SIRS State Reconstruction
cfg.state_reconstruction.method = "reported_case_sirs_proxy";
cfg.state_reconstruction.reference_population = 10379295;
cfg.state_reconstruction.reference_population_source = ...
    "Statistics Sweden: population at the end of 2020.";
cfg.state_reconstruction.reporting_fraction = 1.0;
cfg.state_reconstruction.effective_population = partA_cfg.sirs.pop_size;
cfg.state_reconstruction.effective_population_source = ...
    "Part A effective SIRS simulation population.";
cfg.state_reconstruction.gamma = partA_cfg.sirs.gamma;
cfg.state_reconstruction.xi = partA_cfg.sirs.xi;
cfg.state_reconstruction.sirs_parameter_source = ...
    "Part A SIRS transition assumptions.";
cfg.state_reconstruction.min_susceptible = ...
    partA_cfg.sirs.min_susceptible;
cfg.state_reconstruction.lookback_days = 0;
cfg.state_reconstruction.history_assumption = ...
    "No pre-study incidence is used. The SIRS proxy recursion begins immediately before the configured study start date. Renewal estimation begins on the configured study start date, and undefined initial estimates are preserved through Rt_valid_mask.";
cfg.state_reconstruction.initial_infectious = 0;
cfg.state_reconstruction.initial_recovered = 0;
cfg.state_reconstruction.initial_susceptible = ...
    cfg.state_reconstruction.effective_population ...
    - cfg.state_reconstruction.initial_infectious ...
    - cfg.state_reconstruction.initial_recovered;
cfg.state_reconstruction.conservation_tolerance = ...
    1e-8 * cfg.state_reconstruction.effective_population;
cfg.state_reconstruction.state_timing_convention = ...
    "End-of-day state after processing the incidence reported for that date.";

%% 6. Preparation Snapshot
cfg.snapshot.preparation = struct( ...
    "country_name", cfg.country.name, ...
    "country_code", cfg.country.code, ...
    "study_start_date", cfg.study.start_date, ...
    "study_end_date", cfg.study.end_date, ...
    "serial_interval_mean_days", cfg.renewal.serial_interval_mean_days, ...
    "serial_interval_sd_days", cfg.renewal.serial_interval_sd_days, ...
    "serial_interval_max_lag_days", cfg.renewal.serial_interval_max_lag_days, ...
    "min_infectiousness", cfg.renewal.min_infectiousness, ...
    "incidence_preprocessing", cfg.preparation.incidence_preprocessing, ...
    "state_reconstruction_method", cfg.state_reconstruction.method, ...
    "reference_population", cfg.state_reconstruction.reference_population, ...
    "reporting_fraction", cfg.state_reconstruction.reporting_fraction, ...
    "effective_population", cfg.state_reconstruction.effective_population, ...
    "gamma", cfg.state_reconstruction.gamma, ...
    "xi", cfg.state_reconstruction.xi, ...
    "min_susceptible", cfg.state_reconstruction.min_susceptible, ...
    "lookback_days", cfg.state_reconstruction.lookback_days, ...
    "initial_infectious", cfg.state_reconstruction.initial_infectious, ...
    "initial_recovered", cfg.state_reconstruction.initial_recovered, ...
    "conservation_tolerance", cfg.state_reconstruction.conservation_tolerance, ...
    "state_timing_convention", ...
    cfg.state_reconstruction.state_timing_convention);

%% 7. Chronological Validation
cfg.validation.calibration_end_date = datetime(2020, 12, 31);
cfg.validation.test_start_date = datetime(2021, 1, 1);

if cfg.validation.test_start_date ~= ...
        cfg.validation.calibration_end_date + caldays(1)
    error('PARTC_CONFIG:InvalidValidationBoundary', ...
        'The Part C test period must begin one day after calibration ends.');
end

%% 8. Limited Local Configuration Selection
cfg.local_selection.order_radius = 1;
cfg.local_selection.min_window = partA_cfg.forecast.min_window;
cfg.local_selection.step_size = partA_cfg.forecast.step_size;
cfg.local_selection.horizon = partA_cfg.forecast.horizon;
cfg.local_selection.wis_alphas = partA_cfg.forecast.wis_alphas;
cfg.local_selection.num_draws = partA_cfg.intervals.num_draws;
cfg.local_selection.seed = partA_cfg.run.seed;
cfg.local_selection.include_epidemic_seed_variation = ...
    partA_cfg.intervals.include_epidemic_seed_variation;
cfg.local_selection.selection_rule = ...
    "Lowest-complexity local configuration within one standard error of the numerically best mean calibration WIS, with ties resolved by mean WIS and original candidate index.";

%% 9. Artifact Paths
cfg.output.prepared_artifact_dir = fullfile(repoRoot, "data", "partC", "prepared");
cfg.output.prepared_artifact_path = fullfile( ...
    cfg.output.prepared_artifact_dir, "partC_01_prepared_data.mat");
cfg.output.model_selection_dir = fullfile(repoRoot, "results", "partC", "model_selection");

%% 10. Supported Local-Selection Configurations
configuration_template = struct( ...
    "model_type", "", ...
    "exo_mode", "", ...
    "partA_selection_artifact_path", "", ...
    "local_selection_artifact_path", "", ...
    "partA_selection_snapshot", struct(), ...
    "local_selection_snapshot", struct());
configurations = repmat(configuration_template, 1, 2);

configurations(1).model_type = "AR";
configurations(1).exo_mode = "None";
configurations(1).partA_selection_artifact_path = fullfile( ...
    partA_cfg.output.model_selection_dir, ...
    "partA_02_global_hyperparameters_AR_None.mat");
configurations(1).local_selection_artifact_path = fullfile( ...
    cfg.output.model_selection_dir, ...
    "partC_02_local_orders_AR_None.mat");

configurations(2).model_type = "ARX";
configurations(2).exo_mode = "I";
configurations(2).partA_selection_artifact_path = fullfile( ...
    partA_cfg.output.model_selection_dir, ...
    "partA_02_global_hyperparameters_ARX_I.mat");
configurations(2).local_selection_artifact_path = fullfile( ...
    cfg.output.model_selection_dir, ...
    "partC_02_local_orders_ARX_I.mat");

for configuration_index = 1:numel(configurations)
    partA_selection_snapshot = partA_cfg.snapshot.selection;
    partA_selection_snapshot.model_type = ...
        configurations(configuration_index).model_type;
    partA_selection_snapshot.exo_mode = ...
        configurations(configuration_index).exo_mode;
    configurations(configuration_index).partA_selection_snapshot = ...
        partA_selection_snapshot;

    configurations(configuration_index).local_selection_snapshot = struct( ...
        "preparation_snapshot", cfg.snapshot.preparation, ...
        "model_type", configurations(configuration_index).model_type, ...
        "exo_mode", configurations(configuration_index).exo_mode, ...
        "calibration_end_date", cfg.validation.calibration_end_date, ...
        "test_start_date", cfg.validation.test_start_date, ...
        "order_radius", cfg.local_selection.order_radius, ...
        "min_window", cfg.local_selection.min_window, ...
        "step_size", cfg.local_selection.step_size, ...
        "horizon", cfg.local_selection.horizon, ...
        "wis_alphas", cfg.local_selection.wis_alphas, ...
        "num_draws", cfg.local_selection.num_draws, ...
        "seed", cfg.local_selection.seed, ...
        "include_epidemic_seed_variation", ...
        cfg.local_selection.include_epidemic_seed_variation, ...
        "selection_rule", cfg.local_selection.selection_rule);
end

cfg.local_selection.configurations = configurations;
cfg.snapshot.local_selection = ...
    [configurations.local_selection_snapshot];
end
