%PARTC_05_GENERATE_FIGURES Generate Part C strategy figures.
%
%   Description:
%       Loads the processed Swedish COVID real-data artifact, strategy-aware
%       forecast artifacts, and evaluation results. The script generates the
%       final thesis-level Part C figures using the shared visualization
%       helpers. Metric computation and table writing remain in Part C 03.
%
%   Workflow:
%       1. Load processed data, forecast artifacts, and evaluation artifact.
%       2. Draw real-data overview and representative strategy forecasts.
%       3. Draw WIS, horizon, coverage, and interval-width summaries.
%       4. Verify that all required thesis-level figures were written.
%
%   See also PARTC_CONFIG, PARTC_03_EVALUATE_MODELS, BUILD_PLOT_SPEC, ...
%            PLOT_SINGLE_PANEL, PLOT_MULTI_PANEL_FIGURE, EXPORT_FIGURE.
%
% A. M. Kaahin 2026-06-03

%% 1. Initialization
clear; close all; clc;

fprintf('=== Part C Figure Generation ===\n');

cfg = partC_config();
figureDir = cfg.output.fig_dir;
forecastDir = cfg.output.forecast_dir;
processedPath = fullfile(cfg.output.data_processed_dir, ...
    'partC_01_real_data_processed.mat');
evaluationArtifact = fullfile(cfg.output.evaluation_dir, ...
    'partC_evaluation_results.mat');

if ~exist(figureDir, 'dir'), mkdir(figureDir); end
if exist(processedPath, 'file') ~= 2
    error('FIG:MissingProcessedArtifact', ...
        'Missing processed Part C data artifact: %s.', processedPath);
end
if exist(evaluationArtifact, 'file') ~= 2
    error('FIG:MissingEvaluationArtifact', ...
        ['Missing Part C evaluation artifact: %s\n' ...
        'Run scripts/partC/partC_03_evaluate_models.m first.'], ...
        evaluationArtifact);
end

%% 2. Load Existing Artifacts
processed = load(processedPath);
local_validate_processed_data(processed, processedPath);
evaluation_data = load(evaluationArtifact);
window_scores = evaluation_data.window_scores;
summary_tables = evaluation_data.summary_tables;
forecast_records = local_load_forecast_records(forecastDir, cfg);

fprintf('Loaded %d forecast artifact(s) from %s\n', ...
    numel(forecast_records), forecastDir);

generated_figures = strings(0, 1);

%% 3. Thesis-Level Figures
generated_figures = [generated_figures; ...
    local_draw_real_data_overview(figureDir, processed)];
generated_figures = [generated_figures; ...
    local_draw_strategy_wis_distribution(figureDir, window_scores)];
generated_figures = [generated_figures; ...
    local_draw_strategy_mean_wis_by_horizon(cfg, figureDir, ...
    summary_tables.horizon_summary)];
generated_figures = [generated_figures; ...
    local_draw_strategy_coverage_interval_width(figureDir, ...
    summary_tables.interval_summary)];
generated_figures = [generated_figures; ...
    local_draw_forecast_comparison_strategies(cfg, figureDir, processed, ...
    forecast_records)];

required_figures = local_required_thesis_figures(figureDir);
missing_required = required_figures(~isfile(required_figures));
if ~isempty(missing_required)
    error('FIG:MissingRequiredThesisFigures', ...
        'Required Part C thesis figures were not generated: %s.', ...
        char(strjoin(missing_required, ', ')));
end

%% 4. Completion
fprintf('Saved %d figure file(s).\n', numel(generated_figures));
fprintf('Thesis-level Part C figures are under: %s\n', figureDir);
fprintf('=== Part C Figure Generation Complete ===\n\n');

%% 5. Local Functions
function local_validate_processed_data(data, processedPath)
%LOCAL_VALIDATE_PROCESSED_DATA Verify processed Part C data for plotting.
    required_fields = {'t', 'Rt_est', 'I_proxy', 'I_scaled'};
    if ~all(isfield(data, required_fields))
        error('FIG:InvalidProcessedData', ...
            'Processed artifact is missing required fields: %s.', processedPath);
    end
end

function records = local_load_forecast_records(forecastDir, cfg)
%LOCAL_LOAD_FORECAST_RECORDS Load expected Part C forecast artifacts.
    records = repmat(struct('strategy_id', "", 'strategy_name', "", ...
        'model_type', "", 'exo_mode', "", 'path', "", ...
        'forecast_results', []), 0, 1);
    missing = strings(0, 1);

    for s = 1:numel(cfg.strategies)
        for c = 1:numel(cfg.fixed_forecast_cases)
            path = string(fullfile(forecastDir, sprintf( ...
                'partC_forecast_%s_%s_%s.mat', ...
                char(cfg.strategies(s).strategy_id), ...
                char(cfg.fixed_forecast_cases(c).model_type), ...
                char(cfg.fixed_forecast_cases(c).exo_mode))));
            if exist(path, 'file') ~= 2
                missing(end + 1, 1) = path; %#ok<AGROW>
                continue;
            end

            loaded = load(path);
            rec = struct();
            rec.strategy_id = string(loaded.strategy_id);
            rec.strategy_name = string(loaded.strategy_name);
            rec.model_type = string(loaded.model_type);
            rec.exo_mode = string(loaded.exo_mode);
            rec.path = path;
            rec.forecast_results = loaded.forecast_results;
            records(end + 1, 1) = rec; %#ok<AGROW>
        end
    end

    if ~isempty(missing)
        error('FIG:MissingForecastArtifacts', ...
            'Missing expected Part C forecast artifact(s): %s.', ...
            char(strjoin(missing, ', ')));
    end
end

function output_path = local_draw_real_data_overview(figureDir, processed)
%LOCAL_DRAW_REAL_DATA_OVERVIEW Draw the Part C real-data overview.
    spec = build_plot_spec( ...
        'figure_name', "Part C real-data overview", ...
        'title', "", ...
        'shared_x_label', "Time since analysis start (days)", ...
        'font_size', 9, ...
        'axis_label_font_size', 10, ...
        'tick_label_font_size', 8, ...
        'panel_labels', ["(a)", "(b)"], ...
        'panel_label_style', struct('FontSize', 10, 'FontWeight', 'bold'), ...
        'layout', struct('num_rows', 2, 'num_cols', 1), ...
        'legend', struct('visible', false), ...
        'output_path', fullfile(figureDir, 'partC_real_data_overview.png'), ...
        'size_cm', [17.0, 10.0]);

    t = double(processed.t(:));
    colors = local_thesis_color_order();
    panels = repmat(struct('series', local_empty_series(0), ...
        'plot_spec', struct()), 2, 1);

    panels(1).series = local_line_series(t, double(processed.I_scaled(:)), ...
        "Scaled infection proxy", struct('Color', colors(2, :), ...
        'LineWidth', 1.3), 1);
    panels(1).plot_spec = struct('y_label', "Scaled infection proxy");

    panels(2).series = local_line_series(t, double(processed.Rt_est(:)), ...
        "Empirical $R_t$", struct('Color', colors(1, :), ...
        'LineWidth', 1.3), 1);
    panels(2).plot_spec = struct('y_label', "Empirical $R_t$");

    fig = plot_multi_panel_figure(panels, spec);
    output_path = export_figure(fig, spec);
    close(fig);
end

function output_path = local_draw_strategy_wis_distribution(figureDir, window_scores)
%LOCAL_DRAW_STRATEGY_WIS_DISTRIBUTION Draw strategy window-WIS distributions.
    spec = build_plot_spec( ...
        'figure_name', "Part C strategy WIS distribution", ...
        'title', "", ...
        'x_label', "Strategy", ...
        'y_label', "Window WIS", ...
        'font_size', 9, ...
        'axis_label_font_size', 10, ...
        'tick_label_font_size', 8, ...
        'x_tick_rotation', 15, ...
        'legend', struct('location', "northoutside", ...
            'orientation', "horizontal", 'box', "off", 'font_size', 8), ...
        'output_path', fullfile(figureDir, ...
            'partC_strategy_wis_distribution.png'), ...
        'size_cm', [17.0, 8.5]);

    strategy_labels = local_strategy_label(window_scores.StrategyID);
    model_labels = local_model_exo_label(window_scores.Model, window_scores.ExoMode);
    panel.series = local_box_series(strategy_labels, window_scores.WindowWIS, ...
        model_labels, "Window WIS", 1);
    fig = plot_single_panel(panel, spec);
    output_path = export_figure(fig, spec);
    close(fig);
end

function output_path = local_draw_strategy_mean_wis_by_horizon(cfg, figureDir, ...
    horizon_summary)
%LOCAL_DRAW_STRATEGY_MEAN_WIS_BY_HORIZON Draw mean WIS by forecast horizon.
    spec = build_plot_spec( ...
        'figure_name', "Part C mean WIS by horizon", ...
        'title', "", ...
        'shared_x_label', "Forecast horizon, $h$ (days)", ...
        'shared_y_label', "Mean WIS", ...
        'font_size', 9, ...
        'axis_label_font_size', 10, ...
        'tick_label_font_size', 8, ...
        'color_order', local_thesis_color_order(), ...
        'panel_labels', ["(a)", "(b)", "(c)"], ...
        'panel_label_style', struct('FontSize', 10, 'FontWeight', 'bold'), ...
        'layout', struct('num_rows', 3, 'num_cols', 1), ...
        'legend', struct('location', "northeast", 'box', "off", ...
            'font_size', 8), ...
        'output_path', fullfile(figureDir, ...
            'partC_strategy_mean_wis_by_horizon.png'), ...
        'size_cm', [17.0, 14.0]);

    panels = repmat(struct('series', local_empty_series(0), ...
        'plot_spec', struct()), numel(cfg.strategies), 1);
    for s = 1:numel(cfg.strategies)
        rows = horizon_summary(string(horizon_summary.StrategyID) == ...
            string(cfg.strategies(s).strategy_id), :);
        panels(s).series = local_model_horizon_series(rows, cfg);
        panels(s).plot_spec = struct('title', ...
            local_strategy_label(cfg.strategies(s).strategy_id));
    end

    fig = plot_multi_panel_figure(panels, spec);
    output_path = export_figure(fig, spec);
    close(fig);
end

function output_path = local_draw_strategy_coverage_interval_width(figureDir, ...
    interval_summary)
%LOCAL_DRAW_STRATEGY_COVERAGE_INTERVAL_WIDTH Draw interval diagnostics.
    spec = build_plot_spec( ...
        'figure_name', "Part C coverage and interval width", ...
        'title', "", ...
        'shared_x_label', "Nominal coverage", ...
        'font_size', 9, ...
        'axis_label_font_size', 10, ...
        'tick_label_font_size', 8, ...
        'panel_labels', ["(a)", "(b)"], ...
        'panel_label_style', struct('FontSize', 10, 'FontWeight', 'bold'), ...
        'layout', struct('num_rows', 1, 'num_cols', 2), ...
        'legend', struct('location', "northoutside", ...
            'orientation', "horizontal", 'box', "off", 'font_size', 7, ...
            'num_columns', 3), ...
        'output_path', fullfile(figureDir, ...
            'partC_strategy_coverage_interval_width.png'), ...
        'size_cm', [17.0, 8.5]);

    panels = repmat(struct('series', local_empty_series(0), ...
        'plot_spec', struct()), 2, 1);
    coverage_series = local_empty_series(0);
    coverage_series(end + 1, 1) = local_line_series([0; 1], [0; 1], ...
        "Nominal", struct('Color', [0.25, 0.25, 0.25], ...
        'LineStyle', ':', 'LineWidth', 1.0), 1);
    width_series = local_empty_series(0);

    keys = unique(interval_summary(:, {'StrategyID', 'Model', 'ExoMode'}), ...
        'rows', 'stable');
    colors = local_thesis_color_order();
    for i = 1:height(keys)
        rows = interval_summary( ...
            string(interval_summary.StrategyID) == string(keys.StrategyID(i)) & ...
            string(interval_summary.Model) == string(keys.Model(i)) & ...
            string(interval_summary.ExoMode) == string(keys.ExoMode(i)), :);
        rows = sortrows(rows, 'NominalCoverage');
        label = local_strategy_model_label(keys.StrategyID(i), ...
            keys.Model(i), keys.ExoMode(i));
        style = struct('Color', colors(1 + mod(i - 1, size(colors, 1)), :), ...
            'LineStyle', local_strategy_line_style(keys.StrategyID(i)), ...
            'LineWidth', 1.3, 'Marker', 'o', 'MarkerSize', 3.5);
        coverage_series(end + 1, 1) = local_line_series( ...
            rows.NominalCoverage, rows.MeanCoverage, label, style, i + 1); %#ok<AGROW>
        width_series(end + 1, 1) = local_line_series( ...
            rows.NominalCoverage, rows.MeanIntervalWidth, label, style, i); %#ok<AGROW>
    end

    panels(1).series = coverage_series;
    panels(1).plot_spec = struct('y_label', "Empirical coverage", ...
        'x_limits', [0, 1], 'y_limits', [0, 1]);
    panels(2).series = width_series;
    panels(2).plot_spec = struct('y_label', "Mean interval width", ...
        'x_limits', [0, 1]);

    fig = plot_multi_panel_figure(panels, spec);
    output_path = export_figure(fig, spec);
    close(fig);
end

function output_path = local_draw_forecast_comparison_strategies(cfg, ...
    figureDir, processed, records)
%LOCAL_DRAW_FORECAST_COMPARISON_STRATEGIES Draw representative forecasts.
    spec = build_plot_spec( ...
        'figure_name', "Part C forecast strategy comparison", ...
        'title', "", ...
        'shared_x_label', "Time since analysis start (days)", ...
        'shared_y_label', "Empirical $R_t$", ...
        'font_size', 9, ...
        'axis_label_font_size', 10, ...
        'tick_label_font_size', 8, ...
        'panel_labels', ["(a)", "(b)", "(c)"], ...
        'panel_label_style', struct('FontSize', 10, 'FontWeight', 'bold'), ...
        'layout', struct('num_rows', 3, 'num_cols', 1), ...
        'legend', struct('location', "northeast", 'box', "off", ...
            'font_size', 8), ...
        'output_path', fullfile(figureDir, ...
            'partC_forecast_comparison_strategies.png'), ...
        'size_cm', [17.0, 14.0]);

    panels = repmat(struct('series', local_empty_series(0), ...
        'plot_spec', struct()), numel(cfg.strategies), 1);
    t = double(processed.t(:));
    Rt = double(processed.Rt_est(:));
    colors = local_thesis_color_order();

    for s = 1:numel(cfg.strategies)
        strategy_id = string(cfg.strategies(s).strategy_id);
        strategy_records = records([records.strategy_id] == strategy_id);
        series = local_empty_series(numel(strategy_records) + 1);
        series(1) = local_line_series(t, Rt, ...
            "Empirical $R_t$", struct('Color', [0.08, 0.08, 0.08], ...
            'LineWidth', 1.2), 1);

        for r = 1:numel(strategy_records)
            [target_days, median_forecast] = local_extract_fixed_lead( ...
                strategy_records(r).forecast_results, cfg.forecast.plot_lead_time);
            label = local_model_exo_label(strategy_records(r).model_type, ...
                strategy_records(r).exo_mode);
            style = struct('Color', colors(r + 1, :), ...
                'LineStyle', local_model_line_style(strategy_records(r).model_type), ...
                'LineWidth', 1.35, 'Marker', 'o', 'MarkerSize', 3.0);
            series(r + 1) = local_line_series(target_days, ...
                median_forecast, label, style, r + 1);
        end

        panels(s).series = series;
        panels(s).plot_spec = struct('title', local_strategy_label(strategy_id));
    end

    fig = plot_multi_panel_figure(panels, spec);
    output_path = export_figure(fig, spec);
    close(fig);
end

function [target_days, median_forecast] = local_extract_fixed_lead( ...
    forecast_results, lead_time)
%LOCAL_EXTRACT_FIXED_LEAD Extract fixed-lead median forecasts.
    lead_time = round(double(lead_time));
    num_results = numel(forecast_results);
    target_days = nan(num_results, 1);
    median_forecast = nan(num_results, 1);

    for i = 1:num_results
        t_future = double(forecast_results(i).t_future(:));
        pred = double(forecast_results(i).Rt_pred(:));
        if numel(t_future) < lead_time || numel(pred) < lead_time
            continue;
        end
        target_days(i) = t_future(lead_time);
        median_forecast(i) = pred(lead_time);
    end
end

function series = local_model_horizon_series(horizon_summary, cfg)
%LOCAL_MODEL_HORIZON_SERIES Build horizon WIS line series for one strategy.
    colors = local_thesis_color_order();
    series = local_empty_series(0);
    for i = 1:numel(cfg.fixed_forecast_cases)
        rows = horizon_summary( ...
            string(horizon_summary.Model) == string(cfg.fixed_forecast_cases(i).model_type) & ...
            string(horizon_summary.ExoMode) == string(cfg.fixed_forecast_cases(i).exo_mode), :);
        rows = sortrows(rows, 'HorizonIdx');
        label = local_model_exo_label(cfg.fixed_forecast_cases(i).model_type, ...
            cfg.fixed_forecast_cases(i).exo_mode);
        series(end + 1, 1) = local_line_series(rows.HorizonIdx, rows.MeanWIS, ...
            label, struct('Color', colors(i, :), 'LineWidth', 1.4, ...
            'Marker', 'o', 'MarkerSize', 3.5), i); %#ok<AGROW>
    end
end

function labels = local_strategy_label(strategy_id)
%LOCAL_STRATEGY_LABEL Build compact strategy labels.
    ids = string(strategy_id);
    labels = ids;
    labels(ids == "fixed_parameters") = "Fixed-parameter transfer";
    labels(ids == "online_reestimate") = "Online re-estimation";
    labels(ids == "local_order_retuning") = "Local order retuning";
end

function labels = local_model_exo_label(model, exo)
%LOCAL_MODEL_EXO_LABEL Build compact model/exogenous labels.
    labels = string(model) + " / " + string(exo);
end

function label = local_strategy_model_label(strategy_id, model, exo)
%LOCAL_STRATEGY_MODEL_LABEL Build compact strategy/model labels.
    label = local_strategy_label(strategy_id) + ", " + ...
        local_model_exo_label(model, exo);
end

function style = local_strategy_line_style(strategy_id)
%LOCAL_STRATEGY_LINE_STYLE Assign stable line styles by strategy.
    switch char(string(strategy_id))
        case 'fixed_parameters'
            style = '-';
        case 'online_reestimate'
            style = '--';
        otherwise
            style = '-.';
    end
end

function style = local_model_line_style(model_type)
%LOCAL_MODEL_LINE_STYLE Assign stable line styles by model.
    if string(model_type) == "AR"
        style = '--';
    else
        style = '-';
    end
end

function series = local_empty_series(n)
%LOCAL_EMPTY_SERIES Create an empty or preallocated series struct.
    series = repmat(struct('type', "", 'x', [], 'y', [], 'lower', [], ...
        'upper', [], 'group', [], 'label', "", 'style', struct(), ...
        'legend_rank', 1), n, 1);
end

function series = local_line_series(x, y, label, style, legend_rank)
%LOCAL_LINE_SERIES Create a generic line-series definition.
    series = struct('type', "line", 'x', double(x(:)), 'y', double(y(:)), ...
        'lower', [], 'upper', [], 'group', [], 'label', string(label), ...
        'style', style, 'legend_rank', legend_rank);
end

function series = local_box_series(x, y, group, label, legend_rank)
%LOCAL_BOX_SERIES Create a grouped boxchart-series definition.
    series = struct('type', "boxchart", 'x', string(x(:)), ...
        'y', double(y(:)), 'lower', [], 'upper', [], ...
        'group', string(group(:)), 'label', string(label), ...
        'style', struct(), 'legend_rank', legend_rank);
end

function colors = local_thesis_color_order()
%LOCAL_THESIS_COLOR_ORDER Return a compact colourblind-conscious palette.
    colors = [ ...
        0.00, 0.45, 0.70; ...
        0.84, 0.37, 0.00; ...
        0.00, 0.62, 0.45; ...
        0.80, 0.47, 0.65; ...
        0.34, 0.71, 0.91; ...
        0.90, 0.62, 0.00];
end

function required = local_required_thesis_figures(figureDir)
%LOCAL_REQUIRED_THESIS_FIGURES Return required Part C figure paths.
    required = string([ ...
        fullfile(figureDir, 'partC_real_data_overview.png'); ...
        fullfile(figureDir, 'partC_strategy_wis_distribution.png'); ...
        fullfile(figureDir, 'partC_strategy_mean_wis_by_horizon.png'); ...
        fullfile(figureDir, 'partC_strategy_coverage_interval_width.png'); ...
        fullfile(figureDir, 'partC_forecast_comparison_strategies.png')]);
end
