%PARTC_05_GENERATE_FIGURES Generate Part C thesis figures.
%
%   Description:
%       Loads the processed Swedish COVID real-data artifact, canonical Part C
%       forecast artifacts, evaluation artifact, and summary tables. The
%       script then generates thesis-ready Part C figures using the shared
%       visualization helpers. Metric computation and table writing remain in
%       Part C 03.
%
%   Workflow:
%       1. Load processed data, forecast artifacts, evaluation artifact, and
%          summary tables.
%       2. Draw real-data overview and fixed forecast comparisons.
%       3. Draw WIS, horizon, coverage, and interval-width summaries.
%       4. Verify that all required thesis-level figures were written.
%
%   See also PARTC_CONFIG, PARTC_03_EVALUATE_MODELS, BUILD_PLOT_SPEC, ...
%            PLOT_SINGLE_PANEL, PLOT_MULTI_PANEL_FIGURE, EXPORT_FIGURE.
%
% A. M. Kaahin 2026-06-03

%% 1. Initialization
clear; close all; clc;

fprintf('=== Part C Figure Generation ===\n');

cfg = partC_config();
figureDir = cfg.output.fig_dir;
tableDir = cfg.output.table_dir;
forecastDir = cfg.output.forecast_dir;
processedPath = fullfile(cfg.output.data_processed_dir, ...
    'partC_01_real_data_processed.mat');
evaluationArtifact = fullfile(cfg.output.evaluation_dir, ...
    'partC_evaluation_results.mat');

if ~exist(figureDir, 'dir'), mkdir(figureDir); end
if exist(processedPath, 'file') ~= 2
    error('FIG:MissingProcessedArtifact', ...
        'Missing processed Part C data artifact: %s.', processedPath);
end
if exist(evaluationArtifact, 'file') ~= 2
    error('FIG:MissingEvaluationArtifact', ...
        ['Missing Part C evaluation artifact: %s\n' ...
        'Run scripts/partC/partC_03_evaluate_models.m first.'], ...
        evaluationArtifact);
end

%% 2. Load Existing Artifacts
processed = load(processedPath);
local_validate_processed_data(processed, processedPath);
evaluation_data = load(evaluationArtifact);
window_scores = evaluation_data.window_scores;
summary_tables = evaluation_data.summary_tables;
forecast_records = local_load_forecast_records(forecastDir, cfg);

table_cache = struct();
table_cache.model_summary = local_read_table_required( ...
    fullfile(tableDir, 'partC_model_summary.csv'));
table_cache.horizon_summary = local_read_table_required( ...
    fullfile(tableDir, 'partC_horizon_summary.csv'));
table_cache.interval_summary = local_read_table_required( ...
    fullfile(tableDir, 'partC_interval_summary.csv'));

fprintf('Loaded %d forecast artifact(s) from %s\n', ...
    numel(forecast_records), forecastDir);

generated_figures = strings(0, 1);

%% 3. Thesis-Level Figures
generated_figures = [generated_figures; ...
    local_draw_real_data_overview(figureDir, processed)];

for i = 1:numel(forecast_records)
    generated_figures = [generated_figures; ...
        local_draw_forecast_comparison(cfg, figureDir, processed, ...
        forecast_records(i))]; %#ok<AGROW>
end

generated_figures = [generated_figures; ...
    local_draw_model_wis_distribution(figureDir, window_scores)];
generated_figures = [generated_figures; ...
    local_draw_mean_wis_by_horizon(cfg, figureDir, ...
    table_cache.horizon_summary)];
generated_figures = [generated_figures; ...
    local_draw_coverage_interval_width(cfg, figureDir, ...
    table_cache.interval_summary, summary_tables)];

required_figures = local_required_thesis_figures(figureDir);
missing_required = required_figures(~isfile(required_figures));
if ~isempty(missing_required)
    error('FIG:MissingRequiredThesisFigures', ...
        'Required Part C thesis figures were not generated: %s.', ...
        char(strjoin(missing_required, ', ')));
end

%% 4. Completion
fprintf('Saved %d figure file(s).\n', numel(generated_figures));
fprintf('Thesis-level Part C figures are under: %s\n', figureDir);
fprintf('=== Part C Figure Generation Complete ===\n\n');

%% 5. Local Functions
function local_validate_processed_data(data, processedPath)
%LOCAL_VALIDATE_PROCESSED_DATA Verify processed Part C data for plotting.
    required_fields = {'t', 'Rt_est', 'I_proxy', 'I_scaled'};
    if ~all(isfield(data, required_fields))
        error('FIG:InvalidProcessedData', ...
            'Processed artifact is missing required fields: %s.', processedPath);
    end
end

function records = local_load_forecast_records(forecastDir, cfg)
%LOCAL_LOAD_FORECAST_RECORDS Load canonical Part C forecast artifacts.
    files = dir(fullfile(forecastDir, 'partC_forecast_real_*.mat'));
    files = local_sort_dir_by_name(files);
    records = repmat(struct('model_type', "", 'exo_mode', "", ...
        'path', "", 'forecast_results', []), 0, 1);

    for i = 1:numel(files)
        path = string(fullfile(files(i).folder, files(i).name));
        loaded = load(path);
        if ~isfield(loaded, 'model_type') || ~isfield(loaded, 'exo_mode') || ...
                ~isfield(loaded, 'forecast_results')
            continue;
        end
        if ~local_is_fixed_case(loaded, cfg.fixed_forecast_cases)
            continue;
        end

        rec = struct();
        rec.model_type = string(loaded.model_type);
        rec.exo_mode = string(loaded.exo_mode);
        rec.path = path;
        rec.forecast_results = loaded.forecast_results;
        records(end + 1, 1) = rec; %#ok<AGROW>
    end

    if isempty(records)
        error('FIG:NoForecastArtifacts', ...
            'No canonical Part C forecast artifacts found under %s.', forecastDir);
    end
end

function tf = local_is_fixed_case(loaded, fixed_cases)
%LOCAL_IS_FIXED_CASE Return true for the frozen Part C model comparison.
    tf = false;
    for i = 1:numel(fixed_cases)
        tf = tf || ...
            (string(fixed_cases(i).model_type) == string(loaded.model_type) && ...
            string(fixed_cases(i).exo_mode) == string(loaded.exo_mode));
    end
end

function table_data = local_read_table_required(tablePath)
%LOCAL_READ_TABLE_REQUIRED Read a required Part C table.
    if exist(tablePath, 'file') ~= 2
        error('FIG:MissingTable', 'Missing required Part C table: %s.', tablePath);
    end
    table_data = readtable(tablePath, 'VariableNamingRule', 'preserve');
end

function output_path = local_draw_real_data_overview(figureDir, processed)
%LOCAL_DRAW_REAL_DATA_OVERVIEW Draw the Part C real-data overview.
    spec = build_plot_spec( ...
        'figure_name', "Part C real-data overview", ...
        'title', "", ...
        'shared_x_label', "Time since analysis start (days)", ...
        'font_size', 9, ...
        'axis_label_font_size', 10, ...
        'tick_label_font_size', 8, ...
        'panel_labels', ["(a)", "(b)"], ...
        'panel_label_style', struct('FontSize', 10, 'FontWeight', 'bold'), ...
        'layout', struct('num_rows', 2, 'num_cols', 1), ...
        'legend', struct('visible', false), ...
        'output_path', fullfile(figureDir, 'partC_real_data_overview.png'), ...
        'size_cm', [17.0, 10.0]);

    t = double(processed.t(:));
    colors = local_thesis_color_order();
    panels = repmat(struct('series', local_empty_series(0), ...
        'plot_spec', struct()), 2, 1);

    panels(1).series = local_line_series(t, double(processed.I_scaled(:)), ...
        "Scaled infection proxy", struct('Color', colors(2, :), ...
        'LineWidth', 1.3), 1);
    panels(1).plot_spec = struct('y_label', "Scaled infection proxy");

    panels(2).series = local_line_series(t, double(processed.Rt_est(:)), ...
        "Empirical $R_t$", struct('Color', colors(1, :), ...
        'LineWidth', 1.3), 1);
    panels(2).plot_spec = struct('y_label', "Empirical $R_t$");

    fig = plot_multi_panel_figure(panels, spec);
    output_path = export_figure(fig, spec);
    close(fig);
end

function output_path = local_draw_forecast_comparison(cfg, figureDir, processed, record)
%LOCAL_DRAW_FORECAST_COMPARISON Draw fixed-lead forecast comparison.
    model_label = local_model_exo_label(record.model_type, record.exo_mode);
    output_name = sprintf('partC_forecast_comparison_%s_%s.png', ...
        char(record.model_type), char(record.exo_mode));
    interval_labels = string(compose('%d%% PI', ...
        round((1 - sort(double(cfg.forecast.plot_alphas(:)))) * 100)));

    spec = build_plot_spec( ...
        'figure_name', "Part C forecast comparison", ...
        'title', "", ...
        'x_label', "Time since analysis start (days)", ...
        'y_label', "Empirical $R_t$", ...
        'font_size', 9, ...
        'axis_label_font_size', 10, ...
        'tick_label_font_size', 8, ...
        'lead_time', cfg.forecast.plot_lead_time, ...
        'plot_alphas', cfg.forecast.plot_alphas, ...
        'legend', struct('location', "northoutside", ...
            'orientation', "horizontal", 'box', "off", 'font_size', 8, ...
            'num_columns', 4), ...
        'output_path', fullfile(figureDir, output_name), ...
        'size_cm', [17.0, 8.5]);

    [target_days, median_forecast, lower_forecast, upper_forecast, ...
        plot_alphas] = local_extract_fixed_lead(record.forecast_results, ...
        cfg.forecast.plot_lead_time, cfg.forecast.plot_alphas);

    colors = local_thesis_color_order();
    series = local_empty_series(0);

    for j = 1:numel(plot_alphas)
        label = interval_labels(j);
        series(end + 1, 1) = local_ribbon_series(target_days, ...
            lower_forecast(:, j), upper_forecast(:, j), label, ...
            struct('FaceColor', colors(3 + mod(j - 1, 2), :), ...
            'FaceAlpha', 0.16 + 0.10 * j, 'EdgeColor', 'none'), j); %#ok<AGROW>
    end

    series(end + 1, 1) = local_line_series(double(processed.t(:)), ...
        double(processed.Rt_est(:)), "Empirical $R_t$", ...
        struct('Color', [0.08, 0.08, 0.08], 'LineWidth', 1.5), 10);
    series(end + 1, 1) = local_line_series(target_days, median_forecast, ...
        sprintf('%d-day median, %s', cfg.forecast.plot_lead_time, model_label), ...
        struct('Color', colors(2, :), 'LineStyle', '--', ...
        'LineWidth', 1.4, 'Marker', 'o', 'MarkerSize', 3.2), 11);

    panel.series = series;
    fig = plot_single_panel(panel, spec);
    output_path = export_figure(fig, spec);
    close(fig);
end

function output_path = local_draw_model_wis_distribution(figureDir, window_scores)
%LOCAL_DRAW_MODEL_WIS_DISTRIBUTION Draw model-level window WIS distribution.
    spec = build_plot_spec( ...
        'figure_name', "Part C model WIS distribution", ...
        'title', "", ...
        'x_label', "Fixed forecast configuration", ...
        'y_label', "Window WIS", ...
        'font_size', 9, ...
        'axis_label_font_size', 10, ...
        'tick_label_font_size', 8, ...
        'output_path', fullfile(figureDir, 'partC_model_wis_distribution.png'), ...
        'size_cm', [16.0, 8.5]);

    labels = local_model_exo_label(window_scores.Model, window_scores.ExoMode);
    panel.series = local_box_series(labels, window_scores.WindowWIS, ...
        "Window WIS", 1);
    fig = plot_single_panel(panel, spec);
    output_path = export_figure(fig, spec);
    close(fig);
end

function output_path = local_draw_mean_wis_by_horizon(cfg, figureDir, horizon_summary)
%LOCAL_DRAW_MEAN_WIS_BY_HORIZON Draw mean WIS by forecast horizon.
    spec = build_plot_spec( ...
        'figure_name', "Part C mean WIS by horizon", ...
        'title', "", ...
        'x_label', "Forecast horizon, $h$ (days)", ...
        'y_label', "Mean WIS", ...
        'font_size', 9, ...
        'axis_label_font_size', 10, ...
        'tick_label_font_size', 8, ...
        'color_order', local_thesis_color_order(), ...
        'legend', struct('location', "northoutside", ...
            'orientation', "horizontal", 'box', "off", 'font_size', 9), ...
        'output_path', fullfile(figureDir, 'partC_mean_wis_by_horizon.png'), ...
        'size_cm', [17.0, 8.5]);

    panel.series = local_model_horizon_series(horizon_summary, cfg);
    fig = plot_single_panel(panel, spec);
    output_path = export_figure(fig, spec);
    close(fig);
end

function output_path = local_draw_coverage_interval_width(cfg, figureDir, ...
    interval_summary, summary_tables)
%LOCAL_DRAW_COVERAGE_INTERVAL_WIDTH Draw coverage and interval-width diagnostics.
    if nargin < 4 || ~isstruct(summary_tables) || ...
            ~isfield(summary_tables, 'interval_summary')
        error('FIG:MissingIntervalSummary', ...
            'Part C interval summary is required for diagnostics.');
    end

    spec = build_plot_spec( ...
        'figure_name', "Part C coverage and interval width", ...
        'title', "", ...
        'shared_x_label', "Nominal coverage", ...
        'font_size', 9, ...
        'axis_label_font_size', 10, ...
        'tick_label_font_size', 8, ...
        'panel_labels', ["(a)", "(b)"], ...
        'panel_label_style', struct('FontSize', 10, 'FontWeight', 'bold'), ...
        'layout', struct('num_rows', 1, 'num_cols', 2), ...
        'legend', struct('location', "northoutside", ...
            'orientation', "horizontal", 'box', "off", 'font_size', 8), ...
        'output_path', fullfile(figureDir, ...
            'partC_coverage_interval_width.png'), ...
        'size_cm', [17.0, 8.5]);

    colors = local_thesis_color_order();
    model_cases = cfg.fixed_forecast_cases;
    panels = repmat(struct('series', local_empty_series(0), ...
        'plot_spec', struct()), 2, 1);

    coverage_series = local_empty_series(0);
    coverage_series(end + 1, 1) = local_line_series([0; 1], [0; 1], ...
        "Nominal", struct('Color', [0.25, 0.25, 0.25], ...
        'LineStyle', ':', 'LineWidth', 1.0), 1);
    width_series = local_empty_series(0);

    for i = 1:numel(model_cases)
        rows = interval_summary( ...
            string(interval_summary.Model) == string(model_cases(i).model_type) & ...
            string(interval_summary.ExoMode) == string(model_cases(i).exo_mode), :);
        rows = sortrows(rows, 'NominalCoverage');
        label = local_model_exo_label(model_cases(i).model_type, ...
            model_cases(i).exo_mode);
        coverage_series(end + 1, 1) = local_line_series( ...
            rows.NominalCoverage, rows.MeanCoverage, label, ...
            struct('Color', colors(i, :), 'LineWidth', 1.4, ...
            'Marker', 'o', 'MarkerSize', 4), i + 1); %#ok<AGROW>
        width_series(end + 1, 1) = local_line_series( ...
            rows.NominalCoverage, rows.MeanIntervalWidth, label, ...
            struct('Color', colors(i, :), 'LineWidth', 1.4, ...
            'Marker', 'o', 'MarkerSize', 4), i); %#ok<AGROW>
    end

    panels(1).series = coverage_series;
    panels(1).plot_spec = struct('y_label', "Empirical coverage", ...
        'x_limits', [0, 1], 'y_limits', [0, 1]);
    panels(2).series = width_series;
    panels(2).plot_spec = struct('y_label', "Mean interval width", ...
        'x_limits', [0, 1]);

    fig = plot_multi_panel_figure(panels, spec);
    output_path = export_figure(fig, spec);
    close(fig);
end

function [target_days, median_forecast, lower_forecast, upper_forecast, plot_alphas] = ...
    local_extract_fixed_lead(forecast_results, lead_time, requested_alphas)
%LOCAL_EXTRACT_FIXED_LEAD Extract fixed-lead median and intervals.
    lead_time = round(double(lead_time));
    plot_alphas = sort(double(requested_alphas(:)'), 'ascend');
    num_results = numel(forecast_results);
    num_alphas = numel(plot_alphas);
    target_days = nan(num_results, 1);
    median_forecast = nan(num_results, 1);
    lower_forecast = nan(num_results, num_alphas);
    upper_forecast = nan(num_results, num_alphas);

    for i = 1:num_results
        t_future = double(forecast_results(i).t_future(:));
        pred = double(forecast_results(i).Rt_pred(:));
        if numel(t_future) < lead_time || numel(pred) < lead_time
            continue;
        end

        target_days(i) = t_future(lead_time);
        median_forecast(i) = pred(lead_time);
        stored_alphas = reshape(double(forecast_results(i).interval_alphas), 1, []);
        for j = 1:num_alphas
            idx_alpha = local_alpha_index(stored_alphas, plot_alphas(j));
            if isempty(idx_alpha)
                continue;
            end
            lower_forecast(i, j) = forecast_results(i).lower_bounds(lead_time, idx_alpha);
            upper_forecast(i, j) = forecast_results(i).upper_bounds(lead_time, idx_alpha);
        end
    end
end

function idx = local_alpha_index(stored_alphas, target_alpha)
%LOCAL_ALPHA_INDEX Find a stored predictive interval alpha.
    [min_diff, idx] = min(abs(stored_alphas - target_alpha));
    if isempty(idx) || min_diff > 1e-8
        idx = [];
    end
end

function series = local_model_horizon_series(horizon_summary, cfg)
%LOCAL_MODEL_HORIZON_SERIES Build horizon WIS line series.
    colors = local_thesis_color_order();
    model_cases = cfg.fixed_forecast_cases;
    series = local_empty_series(0);
    for i = 1:numel(model_cases)
        rows = horizon_summary( ...
            string(horizon_summary.Model) == string(model_cases(i).model_type) & ...
            string(horizon_summary.ExoMode) == string(model_cases(i).exo_mode), :);
        rows = sortrows(rows, 'HorizonIdx');
        label = local_model_exo_label(model_cases(i).model_type, ...
            model_cases(i).exo_mode);
        series(end + 1, 1) = local_line_series(rows.HorizonIdx, rows.MeanWIS, ...
            label, struct('Color', colors(i, :), 'LineWidth', 1.5, ...
            'Marker', 'o', 'MarkerSize', 4), i); %#ok<AGROW>
    end
end

function labels = local_model_exo_label(model, exo)
%LOCAL_MODEL_EXO_LABEL Build compact model/exogenous labels.
    labels = string(model) + " / " + string(exo);
end

function series = local_empty_series(n)
%LOCAL_EMPTY_SERIES Create an empty or preallocated series struct.
    series = repmat(struct('type', "", 'x', [], 'y', [], 'lower', [], ...
        'upper', [], 'label', "", 'style', struct(), 'legend_rank', 1), n, 1);
end

function series = local_line_series(x, y, label, style, legend_rank)
%LOCAL_LINE_SERIES Create a generic line-series definition.
    series = struct('type', "line", 'x', double(x(:)), 'y', double(y(:)), ...
        'lower', [], 'upper', [], 'label', string(label), 'style', style, ...
        'legend_rank', legend_rank);
end

function series = local_ribbon_series(x, lower, upper, label, style, legend_rank)
%LOCAL_RIBBON_SERIES Create a generic interval-ribbon definition.
    series = struct('type', "ribbon", 'x', double(x(:)), 'y', [], ...
        'lower', double(lower(:)), 'upper', double(upper(:)), ...
        'label', string(label), 'style', style, 'legend_rank', legend_rank);
end

function series = local_box_series(x, y, label, legend_rank)
%LOCAL_BOX_SERIES Create a generic boxchart-series definition.
    series = struct('type', "boxchart", 'x', string(x(:)), ...
        'y', double(y(:)), 'lower', [], 'upper', [], ...
        'label', string(label), 'style', struct(), ...
        'legend_rank', legend_rank);
end

function colors = local_thesis_color_order()
%LOCAL_THESIS_COLOR_ORDER Return a compact colourblind-conscious palette.
    colors = [ ...
        0.00, 0.45, 0.70; ...
        0.84, 0.37, 0.00; ...
        0.00, 0.62, 0.45; ...
        0.80, 0.47, 0.65; ...
        0.34, 0.71, 0.91; ...
        0.90, 0.62, 0.00];
end

function required = local_required_thesis_figures(figureDir)
%LOCAL_REQUIRED_THESIS_FIGURES Return required Part C figure paths.
    required = string([ ...
        fullfile(figureDir, 'partC_real_data_overview.png'); ...
        fullfile(figureDir, 'partC_forecast_comparison_AR_None.png'); ...
        fullfile(figureDir, 'partC_forecast_comparison_ARX_I.png'); ...
        fullfile(figureDir, 'partC_model_wis_distribution.png'); ...
        fullfile(figureDir, 'partC_mean_wis_by_horizon.png'); ...
        fullfile(figureDir, 'partC_coverage_interval_width.png')]);
end

function files = local_sort_dir_by_name(files)
%LOCAL_SORT_DIR_BY_NAME Sort a dir struct by name.
    [~, order] = sort({files.name});
    files = files(order);
end
