%PARTC_04_EVALUATE_FORECASTS Evaluate held-out Part C Rt forecasts.
%
%   Description:
%       Evaluates the six canonical Part C held-out forecast artifacts against
%       the operational Rt estimate derived from reported incidence. Computes
%       WIS, median point-error diagnostics, empirical interval coverage, and
%       interval width by origin, lead time, interval level, model, and
%       strategy. Matched strategy comparisons are descriptive because the
%       seven-day origin spacing produces overlapping fourteen-day horizons.
%
%   Workflow:
%       1. Load and validate the prepared-data and forecast artifacts.
%       2. Score every held-out origin, lead time, and interval level.
%       3. Build grouped summaries and matched descriptive comparisons.
%       4. Verify current online-strategy equivalence without merging strategies.
%       5. Validate and transactionally promote one MAT artifact and eight CSVs.
%
%   See also PARTC_CONFIG, PARTC_01_PREPARE_DATA, ...
%            PARTC_03_RUN_FORECASTS, COMPUTE_WIS, ...
%            COMPUTE_POINT_ERROR, COMPUTE_INTERVAL_DIAGNOSTICS.
%
% A. M. Kaahin 2026-08-06

%% 1. Initialization
clear; close all; clc;

fprintf('=== Part C Held-Out Forecast Evaluation ===\n');

cfg = partC_config();
local_validate_evaluation_configuration(cfg);
local_require_scoring_dependencies();

prepared_artifact_path = cfg.output.prepared_artifact_path;
forecast_artifact_paths = cfg.evaluation.expected_forecast_artifact_paths;
target_description = ...
    "Operational Rt estimate derived from held-out reported-incidence data; not known epidemiological truth.";

%% 2. Load and Validate Source Artifacts
prepared = local_load_prepared_data(cfg);
artifacts = local_load_forecast_artifacts(prepared, cfg);
local_validate_artifact_set(artifacts, prepared, cfg);

fprintf('Validated six canonical forecast artifacts.\n');
fprintf('Held-out origins per artifact: %d\n', numel(artifacts{1}.results));

%% 3. Score All Forecasts
[origin_scores, horizon_scores, interval_scores, interval_pointwise] = ...
    local_score_artifacts(artifacts);

fprintf('Horizon rows: %d\n', height(horizon_scores));
fprintf('Interval rows: %d\n', height(interval_scores));

%% 4. Build Summaries and Comparisons
summaries = struct();
summaries.strategy_summary = local_strategy_summary(origin_scores);
summaries.horizon_summary = local_horizon_summary(horizon_scores);
summaries.interval_summary = local_interval_summary(interval_pointwise);

pairwise_comparisons = local_pairwise_comparisons(origin_scores, cfg);
online_equivalence = local_online_equivalence(artifacts, cfg);

%% 5. Validate Evaluation Results
local_validate_evaluation_results( ...
    origin_scores, horizon_scores, interval_scores, interval_pointwise, ...
    summaries, pairwise_comparisons, online_equivalence, artifacts, cfg);

evaluation_snapshot = cfg.snapshot.evaluation;
preparation_snapshot = prepared.preparation_snapshot;
forecast_snapshot = cfg.snapshot.forecast;

evaluation_payload = struct( ...
    "origin_scores", origin_scores, ...
    "horizon_scores", horizon_scores, ...
    "interval_scores", interval_scores, ...
    "summaries", summaries, ...
    "pairwise_comparisons", pairwise_comparisons, ...
    "online_equivalence", online_equivalence, ...
    "forecast_artifact_paths", forecast_artifact_paths, ...
    "prepared_artifact_path", prepared_artifact_path, ...
    "preparation_snapshot", preparation_snapshot, ...
    "forecast_snapshot", forecast_snapshot, ...
    "evaluation_snapshot", evaluation_snapshot, ...
    "target_description", target_description);

%% 6. Stage, Validate, and Promote Outputs
evaluation_artifact_path = fullfile( ...
    cfg.output.evaluation_dir, "partC_04_evaluation_results.mat");
csv_names = [ ...
    "partC_04_origin_scores.csv"
    "partC_04_horizon_scores.csv"
    "partC_04_interval_scores.csv"
    "partC_04_strategy_summary.csv"
    "partC_04_horizon_summary.csv"
    "partC_04_interval_summary.csv"
    "partC_04_pairwise_comparisons.csv"
    "partC_04_online_equivalence.csv"];
csv_tables = { ...
    origin_scores
    horizon_scores
    interval_scores
    summaries.strategy_summary
    summaries.horizon_summary
    summaries.interval_summary
    pairwise_comparisons
    online_equivalence};

csv_paths = fullfile(cfg.output.table_dir, csv_names);
local_commit_outputs( ...
    evaluation_payload, evaluation_artifact_path, ...
    csv_tables, csv_paths, artifacts, interval_pointwise, cfg);

%% 7. Completion Report
disp(summaries.strategy_summary);
disp(online_equivalence);
fprintf('Saved MAT artifact: %s\n', evaluation_artifact_path);
for csv_index = 1:numel(csv_paths)
    fprintf('Saved CSV: %s\n', csv_paths(csv_index));
end

fprintf('=== Part C Held-Out Forecast Evaluation Complete ===\n\n');

%% 8. Local Functions
function local_validate_evaluation_configuration(cfg)
%LOCAL_VALIDATE_EVALUATION_CONFIGURATION Validate the fixed evaluation protocol.
required_snapshot_fields = { ...
    'forecast_snapshot'
    'target_identifier'
    'metric_identifiers'
    'grouping_dimensions'
    'required_strategy_identifiers'
    'required_supported_pairs'
    'expected_forecast_artifact_names'
    'retain_all_origins'
    'pairwise_comparison_policy'
    'wis_equality_tolerance'
    };
expected_names = [ ...
    "partC_03_forecast_AR_None_partA_online_fit.mat"
    "partC_03_forecast_AR_None_local_online_fit.mat"
    "partC_03_forecast_AR_None_partA_fixed_fit.mat"
    "partC_03_forecast_ARX_I_partA_online_fit.mat"
    "partC_03_forecast_ARX_I_local_online_fit.mat"
    "partC_03_forecast_ARX_I_partA_fixed_fit.mat"];

valid = cfg.evaluation.target_identifier == "target_Rt_estimated" && ...
    isequal(cfg.evaluation.expected_forecast_artifact_names, ...
    expected_names) && ...
    isequal(cfg.evaluation.expected_forecast_artifact_paths, ...
    fullfile(cfg.output.forecast_dir, expected_names)) && ...
    cfg.evaluation.retain_all_origins && ...
    isnumeric(cfg.evaluation.wis_equality_tolerance) && ...
    isscalar(cfg.evaluation.wis_equality_tolerance) && ...
    isfinite(cfg.evaluation.wis_equality_tolerance) && ...
    cfg.evaluation.wis_equality_tolerance >= 0 && ...
    all(isfield(cfg.snapshot.evaluation, required_snapshot_fields)) && ...
    isequaln(cfg.snapshot.evaluation.forecast_snapshot, ...
    cfg.snapshot.forecast);

if ~valid
    error('PARTC_04:InvalidEvaluationConfiguration', ...
        'The Part C evaluation configuration does not satisfy the required protocol.');
end
end

function local_require_scoring_dependencies()
%LOCAL_REQUIRE_SCORING_DEPENDENCIES Require the established shared metrics.
required_functions = [ ...
    "compute_wis"
    "compute_point_error"
    "compute_interval_diagnostics"];

for function_index = 1:numel(required_functions)
    if isempty(which(required_functions(function_index)))
        error('PARTC_04:MissingScoringDependency', ...
            'Required scoring function is unavailable: %s.', ...
            required_functions(function_index));
    end
end
end

function prepared = local_load_prepared_data(cfg)
%LOCAL_LOAD_PREPARED_DATA Load and validate the Script 1 artifact.
prepared_artifact_path = cfg.output.prepared_artifact_path;

if exist(prepared_artifact_path, 'file') ~= 2
    error('PARTC_04:MissingPreparedArtifact', ...
        'Missing prepared Part C artifact: %s. Run Part C Script 1 first.', ...
        prepared_artifact_path);
end

loaded = load(prepared_artifact_path);
required_fields = { ...
    'dates'
    'Rt_estimated'
    'Rt_valid_mask'
    'preparation_snapshot'
    };

if ~all(isfield(loaded, required_fields))
    missing_fields = required_fields(~isfield(loaded, required_fields));
    error('PARTC_04:MissingPreparedFields', ...
        'Prepared Part C artifact is missing fields: %s.', ...
        strjoin(string(missing_fields), ', '));
end

dates = loaded.dates;
Rt_estimated = loaded.Rt_estimated;
Rt_valid_mask = loaded.Rt_valid_mask;

valid_dates = isdatetime(dates) && iscolumn(dates) && ...
    ~any(isnat(dates)) && numel(unique(dates)) == numel(dates) && ...
    all(diff(dates) == days(1));
valid_signals = isnumeric(Rt_estimated) && isreal(Rt_estimated) && ...
    iscolumn(Rt_estimated) && islogical(Rt_valid_mask) && ...
    iscolumn(Rt_valid_mask) && ...
    numel(Rt_estimated) == numel(dates) && ...
    numel(Rt_valid_mask) == numel(dates);

if ~valid_dates
    error('PARTC_04:InvalidPreparedDates', ...
        'Prepared dates must be a unique, ordered, daily datetime column vector.');
end

if ~valid_signals
    error('PARTC_04:InvalidPreparedSignals', ...
        'Prepared Rt estimates and validity mask must match the dates vector contract.');
end

expected_valid_mask = isfinite(Rt_estimated) & Rt_estimated > 0;
if ~isequal(Rt_valid_mask, expected_valid_mask)
    error('PARTC_04:EstimatedRtMaskMismatch', ...
        'Rt_valid_mask must equal isfinite(Rt_estimated) & Rt_estimated > 0 exactly.');
end

if dates(1) ~= cfg.study.start_date || dates(end) ~= cfg.study.end_date
    error('PARTC_04:PreparedStudyPeriodMismatch', ...
        'Prepared dates must match the configured Part C study period exactly.');
end

if ~isequaln(loaded.preparation_snapshot, cfg.snapshot.preparation)
    error('PARTC_04:PreparationSnapshotMismatch', ...
        'Prepared data do not match the configured preparation snapshot.');
end

prepared = struct( ...
    "dates", dates, ...
    "Rt_estimated", Rt_estimated, ...
    "Rt_valid_mask", Rt_valid_mask, ...
    "preparation_snapshot", loaded.preparation_snapshot, ...
    "artifact_path", prepared_artifact_path);
end

function artifacts = local_load_forecast_artifacts(prepared, cfg)
%LOCAL_LOAD_FORECAST_ARTIFACTS Load exactly the six configured artifacts.
artifact_paths = cfg.evaluation.expected_forecast_artifact_paths;
artifacts = cell(numel(artifact_paths), 1);

for artifact_index = 1:numel(artifact_paths)
    artifact_path = artifact_paths(artifact_index);
    if exist(artifact_path, 'file') ~= 2
        error('PARTC_04:MissingForecastArtifact', ...
            'Missing required forecast artifact: %s. Run Part C Script 3 first.', ...
            artifact_path);
    end

    artifact = load(artifact_path);
    local_validate_forecast_artifact( ...
        artifact, artifact_path, artifact_index, prepared, cfg);
    artifacts{artifact_index} = artifact;
end
end

function local_validate_forecast_artifact( ...
        artifact, artifact_path, artifact_index, prepared, cfg)
%LOCAL_VALIDATE_FORECAST_ARTIFACT Validate one canonical Script 3 artifact.
required_artifact_fields = { ...
    'model_type'
    'exo_mode'
    'strategy'
    'strategy_description'
    'configuration_source'
    'parameter_update_mode'
    'forecast_configuration'
    'partA_selected_configuration'
    'local_selected_configuration'
    'selection_artifact_path'
    'prepared_artifact_path'
    'calibration_end_date'
    'test_start_date'
    'study_end_date'
    'wis_alphas'
    'results'
    'fixed_fit_info'
    'preparation_snapshot'
    'local_selection_snapshot'
    'forecast_snapshot'
    };
required_result_fields = { ...
    'origin_index'
    'origin_date'
    'target_indices'
    'target_dates'
    'target_Rt_estimated'
    'forecast_median'
    'forecast_lower'
    'forecast_upper'
    'fit_AICc'
    'resample_seed'
    'epidemic_seed'
    };

if ~all(isfield(artifact, required_artifact_fields))
    missing_fields = required_artifact_fields( ...
        ~isfield(artifact, required_artifact_fields));
    error('PARTC_04:MissingForecastFields', ...
        'Forecast artifact %s is missing fields: %s.', ...
        artifact_path, strjoin(string(missing_fields), ', '));
end

[expected_model, expected_exo, expected_strategy] = ...
    local_expected_identity(artifact_index);
[~, actual_name, actual_extension] = fileparts(artifact_path);
actual_filename = string(actual_name) + string(actual_extension);

if actual_filename ~= ...
        cfg.evaluation.expected_forecast_artifact_names(artifact_index)
    error('PARTC_04:NoncanonicalForecastFilename', ...
        'Forecast artifact path is not canonical: %s.', artifact_path);
end

identity_matches = string(artifact.model_type) == expected_model && ...
    string(artifact.exo_mode) == expected_exo && ...
    string(artifact.strategy) == expected_strategy;
if ~identity_matches
    error('PARTC_04:ForecastIdentityMismatch', ...
        'Forecast artifact identity does not match canonical file %s.', ...
        actual_filename);
end

pair_index = local_pair_index(expected_model, expected_exo, cfg);
strategy_index = find( ...
    [cfg.final_forecast.strategies.identifier].' == expected_strategy, 1);
expected_strategy_config = cfg.final_forecast.strategies(strategy_index);

if string(artifact.strategy_description) ~= ...
        expected_strategy_config.description || ...
        string(artifact.configuration_source) ~= ...
        expected_strategy_config.configuration_source || ...
        string(artifact.parameter_update_mode) ~= ...
        expected_strategy_config.parameter_update_mode
    error('PARTC_04:StrategyMetadataMismatch', ...
        'Strategy metadata is incompatible with %s.', actual_filename);
end

snapshot_matches = isequaln(artifact.preparation_snapshot, ...
    cfg.snapshot.preparation) && ...
    isequaln(artifact.local_selection_snapshot, ...
    cfg.snapshot.local_selection(pair_index)) && ...
    isequaln(artifact.forecast_snapshot, cfg.snapshot.forecast);
path_matches = string(artifact.prepared_artifact_path) == ...
    string(prepared.artifact_path) && ...
    string(artifact.selection_artifact_path) == string( ...
    cfg.final_forecast.configurations(pair_index).selection_artifact_path);
date_matches = artifact.calibration_end_date == ...
    cfg.validation.calibration_end_date && ...
    artifact.test_start_date == cfg.validation.test_start_date && ...
    artifact.study_end_date == cfg.study.end_date;

if ~snapshot_matches || ~path_matches || ~date_matches
    error('PARTC_04:ForecastProvenanceMismatch', ...
        'Forecast artifact provenance is incompatible with %s.', ...
        actual_filename);
end

local_validate_model_configuration( ...
    artifact.partA_selected_configuration, expected_model, ...
    'partA_selected_configuration');
local_validate_model_configuration( ...
    artifact.local_selected_configuration, expected_model, ...
    'local_selected_configuration');
local_validate_model_configuration( ...
    artifact.forecast_configuration, expected_model, ...
    'forecast_configuration');

if expected_strategy == "local_online_fit"
    expected_configuration = artifact.local_selected_configuration;
else
    expected_configuration = artifact.partA_selected_configuration;
end

if ~isequal(artifact.forecast_configuration, expected_configuration)
    error('PARTC_04:StrategyConfigurationMismatch', ...
        'Strategy %s does not use its required selected configuration.', ...
        expected_strategy);
end

if expected_strategy == "partA_fixed_fit"
    local_validate_fixed_fit_info(artifact.fixed_fit_info, ...
        artifact.partA_selected_configuration, prepared, cfg);
else
    valid_empty_fit = isstruct(artifact.fixed_fit_info) && ...
        isscalar(artifact.fixed_fit_info) && ...
        isempty(fieldnames(artifact.fixed_fit_info));
    if ~valid_empty_fit
        error('PARTC_04:UnexpectedOnlineFixedFit', ...
            'Online strategy %s must have empty fixed-fit information.', ...
            expected_strategy);
    end
end

alphas = artifact.wis_alphas;
valid_alphas = isnumeric(alphas) && isreal(alphas) && ...
    iscolumn(alphas) && all(isfinite(alphas)) && ...
    all(alphas > 0 & alphas < 1) && ...
    numel(unique(alphas)) == numel(alphas) && ...
    isequal(alphas, cfg.final_forecast.wis_alphas);
if ~valid_alphas
    error('PARTC_04:InvalidAlphaLevels', ...
        'Forecast artifact %s has invalid or incompatible WIS alpha levels.', ...
        actual_filename);
end

if ~isstruct(artifact.results) || ~iscolumn(artifact.results) || ...
        numel(artifact.results) ~= 22 || ...
        ~isequal(fieldnames(artifact.results), required_result_fields)
    error('PARTC_04:InvalidResultContract', ...
        'Forecast artifact %s must contain 22 results with the common field contract.', ...
        actual_filename);
end

for origin_position = 1:numel(artifact.results)
    local_validate_forecast_result( ...
        artifact.results(origin_position), artifact, origin_position, ...
        prepared, cfg);
end
end

function [model, exo_mode, strategy] = local_expected_identity(index)
%LOCAL_EXPECTED_IDENTITY Return the canonical identity for one file position.
models = ["AR"; "AR"; "AR"; "ARX"; "ARX"; "ARX"];
exo_modes = ["None"; "None"; "None"; "I"; "I"; "I"];
strategies = [ ...
    "partA_online_fit"
    "local_online_fit"
    "partA_fixed_fit"
    "partA_online_fit"
    "local_online_fit"
    "partA_fixed_fit"];
model = models(index);
exo_mode = exo_modes(index);
strategy = strategies(index);
end

function pair_index = local_pair_index(model, exo_mode, cfg)
%LOCAL_PAIR_INDEX Find one configured model and exogenous-input pair.
models = [cfg.final_forecast.configurations.model_type].';
exo_modes = [cfg.final_forecast.configurations.exo_mode].';
pair_index = find(models == model & exo_modes == exo_mode);

if ~isscalar(pair_index)
    error('PARTC_04:UnsupportedModelPair', ...
        'Expected one configured entry for %s/%s.', model, exo_mode);
end
end

function local_validate_model_configuration(configuration, model, field_name)
%LOCAL_VALIDATE_MODEL_CONFIGURATION Validate an AR or ARX order vector.
valid_values = isnumeric(configuration) && isreal(configuration) && ...
    all(isfinite(configuration)) && all(configuration > 0) && ...
    all(configuration == fix(configuration));

if model == "AR"
    valid_shape = isscalar(configuration);
else
    valid_shape = isequal(size(configuration), [1, 3]);
end

if ~valid_values || ~valid_shape
    error('PARTC_04:InvalidForecastConfiguration', ...
        '%s has an invalid shape or value for model %s.', ...
        field_name, model);
end
end

function local_validate_fixed_fit_info(fit_info, configuration, prepared, cfg)
%LOCAL_VALIDATE_FIXED_FIT_INFO Validate calibration-only fixed-fit metadata.
required_fields = { ...
    'configuration'
    'A_coefficients'
    'B_coefficients'
    'max_lag'
    'centred_calibration_residuals'
    'residual_count'
    'calibration_AICc'
    'calibration_start_date'
    'calibration_end_date'
    };

valid = isstruct(fit_info) && isscalar(fit_info) && ...
    all(isfield(fit_info, required_fields)) && ...
    isequal(fit_info.configuration, configuration) && ...
    isnumeric(fit_info.A_coefficients) && ...
    all(isfinite(fit_info.A_coefficients)) && ...
    isnumeric(fit_info.B_coefficients) && ...
    all(isfinite(fit_info.B_coefficients)) && ...
    isnumeric(fit_info.max_lag) && isscalar(fit_info.max_lag) && ...
    isfinite(fit_info.max_lag) && fit_info.max_lag > 0 && ...
    isnumeric(fit_info.centred_calibration_residuals) && ...
    iscolumn(fit_info.centred_calibration_residuals) && ...
    all(isfinite(fit_info.centred_calibration_residuals)) && ...
    fit_info.residual_count == ...
    numel(fit_info.centred_calibration_residuals) && ...
    fit_info.residual_count >= 2 && ...
    isnumeric(fit_info.calibration_AICc) && ...
    isscalar(fit_info.calibration_AICc) && ...
    isfinite(fit_info.calibration_AICc) && ...
    fit_info.calibration_start_date == ...
    prepared.dates(find(prepared.Rt_valid_mask, 1)) && ...
    fit_info.calibration_end_date == datetime(2020, 12, 31) && ...
    fit_info.calibration_end_date == cfg.validation.calibration_end_date;

if ~valid
    error('PARTC_04:InvalidFixedFitMetadata', ...
        'Fixed strategies must contain valid calibration-only fitted-model metadata.');
end
end

function local_validate_forecast_result( ...
        result, artifact, origin_position, prepared, cfg)
%LOCAL_VALIDATE_FORECAST_RESULT Validate one held-out result structure.
horizon = cfg.final_forecast.horizon;
num_alphas = numel(artifact.wis_alphas);
expected_target_indices = (result.origin_index + (1:horizon)).';

valid_identity = isnumeric(result.origin_index) && ...
    isscalar(result.origin_index) && isfinite(result.origin_index) && ...
    result.origin_index == fix(result.origin_index) && ...
    isdatetime(result.origin_date) && isscalar(result.origin_date) && ...
    result.origin_date == prepared.dates(result.origin_index) && ...
    isequal(result.target_indices, expected_target_indices) && ...
    isequal(result.target_dates, prepared.dates(expected_target_indices));
valid_targets = isnumeric(result.target_Rt_estimated) && ...
    iscolumn(result.target_Rt_estimated) && ...
    numel(result.target_Rt_estimated) == horizon && ...
    all(isfinite(result.target_Rt_estimated)) && ...
    all(result.target_Rt_estimated > 0) && ...
    isequal(result.target_Rt_estimated, ...
    prepared.Rt_estimated(expected_target_indices));
valid_forecast = isnumeric(result.forecast_median) && ...
    isequal(size(result.forecast_median), [horizon, 1]) && ...
    all(isfinite(result.forecast_median)) && ...
    all(result.forecast_median > 0) && ...
    isnumeric(result.forecast_lower) && ...
    isnumeric(result.forecast_upper) && ...
    isequal(size(result.forecast_lower), [horizon, num_alphas]) && ...
    isequal(size(result.forecast_upper), [horizon, num_alphas]) && ...
    all(isfinite(result.forecast_lower), 'all') && ...
    all(isfinite(result.forecast_upper), 'all') && ...
    all(result.forecast_lower <= result.forecast_upper, 'all');
valid_metadata = isnumeric(result.fit_AICc) && ...
    isscalar(result.fit_AICc) && isfinite(result.fit_AICc) && ...
    isnumeric(result.resample_seed) && ...
    isscalar(result.resample_seed) && isfinite(result.resample_seed);

if string(artifact.model_type) == "AR"
    valid_metadata = valid_metadata && isempty(result.epidemic_seed);
else
    valid_metadata = valid_metadata && ...
        isnumeric(result.epidemic_seed) && ...
        isscalar(result.epidemic_seed) && ...
        isfinite(result.epidemic_seed);
end

if ~valid_identity || ~valid_targets || ~valid_forecast || ~valid_metadata
    error('PARTC_04:InvalidForecastResult', ...
        'Artifact %s/%s/%s has an invalid result at origin position %d.', ...
        artifact.model_type, artifact.exo_mode, artifact.strategy, ...
        origin_position);
end
end

function local_validate_artifact_set(artifacts, prepared, cfg)
%LOCAL_VALIDATE_ARTIFACT_SET Validate common grids across all six artifacts.
if numel(artifacts) ~= 6 || any(cellfun(@isempty, artifacts))
    error('PARTC_04:IncompleteArtifactSet', ...
        'Exactly six canonical forecast artifacts are required.');
end

reference = artifacts{1};
reference_origin_indices = [reference.results.origin_index].';
reference_origin_dates = [reference.results.origin_date].';

for artifact_index = 1:numel(artifacts)
    artifact = artifacts{artifact_index};
    if ~isequal(artifact.wis_alphas, reference.wis_alphas) || ...
            ~isequal([artifact.results.origin_index].', ...
            reference_origin_indices) || ...
            ~isequal([artifact.results.origin_date].', ...
            reference_origin_dates)
        error('PARTC_04:CommonGridMismatch', ...
            'All six forecast artifacts must use identical alphas and origins.');
    end

    for origin_position = 1:numel(reference.results)
        actual = artifact.results(origin_position);
        expected = reference.results(origin_position);
        common_target = isequal(actual.target_indices, ...
            expected.target_indices) && ...
            isequal(actual.target_dates, expected.target_dates) && ...
            isequal(actual.target_Rt_estimated, ...
            expected.target_Rt_estimated);
        if ~common_target
            error('PARTC_04:CommonTargetMismatch', ...
                'All artifacts must use identical targets at origin position %d.', ...
                origin_position);
        end
    end
end

first_result = reference.results(1);
last_result = reference.results(end);
valid_boundaries = reference_origin_dates(1) == datetime(2020, 12, 31) && ...
    first_result.target_dates(1) == datetime(2021, 1, 1) && ...
    reference_origin_dates(end) == datetime(2021, 5, 27) && ...
    last_result.target_dates(end) == datetime(2021, 6, 10) && ...
    all(vertcat(reference.results.target_dates) >= ...
    cfg.validation.test_start_date) && ...
    all(vertcat(reference.results.target_dates) <= cfg.study.end_date);

if ~valid_boundaries
    error('PARTC_04:HeldOutGridMismatch', ...
        'The common held-out origin and target grid has invalid boundaries.');
end

if ~isequal(reference.results(1).target_Rt_estimated, ...
        prepared.Rt_estimated(reference.results(1).target_indices))
    error('PARTC_04:PreparedTargetMismatch', ...
        'The held-out target does not match the prepared operational Rt estimate.');
end
end

function [origin_scores, horizon_scores, interval_scores, pointwise] = ...
        local_score_artifacts(artifacts)
%LOCAL_SCORE_ARTIFACTS Score every artifact and held-out origin.
num_artifacts = numel(artifacts);
origin_blocks = cell(num_artifacts, 1);
horizon_blocks = cell(num_artifacts, 1);
interval_blocks = cell(num_artifacts, 1);
pointwise_blocks = cell(num_artifacts, 1);

for artifact_index = 1:num_artifacts
    [origin_blocks{artifact_index}, horizon_blocks{artifact_index}, ...
        interval_blocks{artifact_index}, pointwise_blocks{artifact_index}] = ...
        local_score_artifact(artifacts{artifact_index});
end

origin_scores = vertcat(origin_blocks{:});
horizon_scores = vertcat(horizon_blocks{:});
interval_scores = vertcat(interval_blocks{:});
pointwise = vertcat(pointwise_blocks{:});
end

function [origin_table, horizon_table, interval_table, pointwise_table] = ...
        local_score_artifact(artifact)
%LOCAL_SCORE_ARTIFACT Score one model and strategy artifact.
model = string(artifact.model_type);
exo_mode = string(artifact.exo_mode);
strategy = string(artifact.strategy);
strategy_description = string(artifact.strategy_description);
configuration_source = string(artifact.configuration_source);
parameter_update_mode = string(artifact.parameter_update_mode);
forecast_configuration = string(mat2str(artifact.forecast_configuration));
alphas = artifact.wis_alphas(:);
num_origins = numel(artifact.results);
origin_rows = cell(num_origins, 1);
horizon_rows = cell(num_origins, 1);
interval_rows = cell(num_origins, 1);
pointwise_rows = cell(num_origins, 1);

for origin_position = 1:num_origins
    result = artifact.results(origin_position);
    target_Rt = result.target_Rt_estimated(:);
    median_Rt = result.forecast_median(:);
    lower_Rt = result.forecast_lower;
    upper_Rt = result.forecast_upper;

    [pointwise_wis, ~] = compute_wis( ...
        target_Rt, median_Rt, lower_Rt, upper_Rt, alphas);
    point_error = compute_point_error(target_Rt, median_Rt);
    interval_diagnostics = compute_interval_diagnostics( ...
        target_Rt, lower_Rt, upper_Rt, alphas);
    local_validate_metric_outputs( ...
        pointwise_wis, point_error, interval_diagnostics, ...
        numel(target_Rt), numel(alphas), origin_position, artifact);

    horizon = numel(target_Rt);
    num_alphas = numel(alphas);
    origin_rows{origin_position} = table( ...
        model, exo_mode, strategy, strategy_description, ...
        configuration_source, parameter_update_mode, ...
        forecast_configuration, origin_position, result.origin_index, ...
        result.origin_date, result.target_dates(1), result.target_dates(end), ...
        mean(pointwise_wis), point_error.rmse, point_error.mae, ...
        mean(point_error.error), mean(interval_diagnostics.coverage, 'all'), ...
        mean(interval_diagnostics.interval_width, 'all'), result.fit_AICc, ...
        'VariableNames', { ...
        'Model', 'ExoMode', 'Strategy', 'StrategyDescription', ...
        'ConfigurationSource', 'ParameterUpdateMode', ...
        'ForecastConfiguration', 'OriginPosition', 'OriginIndex', ...
        'OriginDate', 'TargetStartDate', 'TargetEndDate', ...
        'MeanWIS', 'RMSE', 'MAE', 'MeanError', 'MeanCoverage', ...
        'MeanIntervalWidth', 'FitAICc'});

    horizon_rows{origin_position} = table( ...
        repmat(model, horizon, 1), repmat(exo_mode, horizon, 1), ...
        repmat(strategy, horizon, 1), ...
        repmat(forecast_configuration, horizon, 1), ...
        repmat(origin_position, horizon, 1), ...
        repmat(result.origin_index, horizon, 1), ...
        repmat(result.origin_date, horizon, 1), (1:horizon).', ...
        result.target_indices, result.target_dates, target_Rt, median_Rt, ...
        point_error.error, point_error.absolute_error, ...
        point_error.squared_error, pointwise_wis, ...
        interval_diagnostics.coverage_mean, ...
        interval_diagnostics.width_mean, ...
        'VariableNames', { ...
        'Model', 'ExoMode', 'Strategy', 'ForecastConfiguration', ...
        'OriginPosition', 'OriginIndex', 'OriginDate', 'LeadTime', ...
        'TargetIndex', 'TargetDate', 'TargetRtEstimated', ...
        'MedianForecast', 'Error', 'AbsoluteError', 'SquaredError', ...
        'WIS', 'MeanCoverage', 'MeanIntervalWidth'});

    empirical_coverage = mean(interval_diagnostics.coverage, 1).';
    mean_interval_width = mean( ...
        interval_diagnostics.interval_width, 1).';
    interval_rows{origin_position} = table( ...
        repmat(model, num_alphas, 1), ...
        repmat(exo_mode, num_alphas, 1), ...
        repmat(strategy, num_alphas, 1), ...
        repmat(forecast_configuration, num_alphas, 1), ...
        repmat(origin_position, num_alphas, 1), ...
        repmat(result.origin_date, num_alphas, 1), ...
        alphas, 1 - alphas, empirical_coverage, ...
        empirical_coverage - (1 - alphas), mean_interval_width, ...
        'VariableNames', { ...
        'Model', 'ExoMode', 'Strategy', 'ForecastConfiguration', ...
        'OriginPosition', 'OriginDate', 'Alpha', 'NominalCoverage', ...
        'EmpiricalCoverage', 'CoverageError', 'MeanIntervalWidth'});

    pointwise_rows{origin_position} = table( ...
        repelem(model, horizon * num_alphas, 1), ...
        repelem(exo_mode, horizon * num_alphas, 1), ...
        repelem(strategy, horizon * num_alphas, 1), ...
        repmat((1:horizon).', num_alphas, 1), ...
        repelem(alphas, horizon, 1), ...
        repelem(1 - alphas, horizon, 1), ...
        interval_diagnostics.coverage(:), ...
        interval_diagnostics.interval_width(:), ...
        'VariableNames', { ...
        'Model', 'ExoMode', 'Strategy', 'LeadTime', 'Alpha', ...
        'NominalCoverage', 'Coverage', 'IntervalWidth'});
end

origin_table = vertcat(origin_rows{:});
horizon_table = vertcat(horizon_rows{:});
interval_table = vertcat(interval_rows{:});
pointwise_table = vertcat(pointwise_rows{:});
end

function local_validate_metric_outputs( ...
        wis, point_error, interval, horizon, num_alphas, ...
        origin_position, artifact)
%LOCAL_VALIDATE_METRIC_OUTPUTS Validate shared scoring-function results.
required_point_fields = { ...
    'error'
    'squared_error'
    'absolute_error'
    'rmse'
    'mae'
    };
required_interval_fields = { ...
    'nominal_coverage'
    'coverage'
    'interval_width'
    'coverage_mean'
    'width_mean'
    };

valid = isequal(size(wis), [horizon, 1]) && all(isfinite(wis)) && ...
    all(isfield(point_error, required_point_fields)) && ...
    isequal(size(point_error.error), [horizon, 1]) && ...
    isequal(size(point_error.squared_error), [horizon, 1]) && ...
    isequal(size(point_error.absolute_error), [horizon, 1]) && ...
    all(isfinite(point_error.error)) && ...
    all(isfinite(point_error.squared_error)) && ...
    all(isfinite(point_error.absolute_error)) && ...
    isfinite(point_error.rmse) && isfinite(point_error.mae) && ...
    all(isfield(interval, required_interval_fields)) && ...
    isequal(size(interval.nominal_coverage), [num_alphas, 1]) && ...
    isequal(size(interval.coverage), [horizon, num_alphas]) && ...
    isequal(size(interval.interval_width), [horizon, num_alphas]) && ...
    isequal(size(interval.coverage_mean), [horizon, 1]) && ...
    isequal(size(interval.width_mean), [horizon, 1]) && ...
    all(isfinite(interval.interval_width), 'all') && ...
    all(interval.interval_width >= 0, 'all') && ...
    all(isfinite(interval.coverage_mean)) && ...
    all(isfinite(interval.width_mean));

if ~valid
    error('PARTC_04:InvalidMetricOutput', ...
        'Shared metrics returned invalid results for %s/%s/%s at origin position %d.', ...
        artifact.model_type, artifact.exo_mode, artifact.strategy, ...
        origin_position);
end
end

function summary = local_strategy_summary(origin_scores)
%LOCAL_STRATEGY_SUMMARY Summarize origin-level scores by strategy identity.
keys = { ...
    'Model'
    'ExoMode'
    'Strategy'
    'ForecastConfiguration'
    'ConfigurationSource'
    'ParameterUpdateMode'
    };
identities = unique(origin_scores(:, keys), 'rows', 'stable');
rows = cell(height(identities), 1);

for group_index = 1:height(identities)
    identity = identities(group_index, :);
    mask = local_identity_mask(origin_scores, identity, keys);
    group = origin_scores(mask, :);
    rows{group_index} = table( ...
        identity.Model, identity.ExoMode, identity.Strategy, ...
        identity.ForecastConfiguration, identity.ConfigurationSource, ...
        identity.ParameterUpdateMode, height(group), ...
        mean(group.MeanWIS), median(group.MeanWIS), ...
        std(group.MeanWIS), min(group.MeanWIS), max(group.MeanWIS), ...
        mean(group.RMSE), mean(group.MAE), mean(group.MeanError), ...
        mean(group.MeanCoverage), mean(group.MeanIntervalWidth), ...
        'VariableNames', { ...
        'Model', 'ExoMode', 'Strategy', 'ForecastConfiguration', ...
        'ConfigurationSource', 'ParameterUpdateMode', 'NumOrigins', ...
        'MeanOriginWIS', 'MedianOriginWIS', 'StdOriginWIS', ...
        'MinOriginWIS', 'MaxOriginWIS', 'MeanRMSE', 'MeanMAE', ...
        'MeanError', 'MeanCoverage', 'MeanIntervalWidth'});
end

summary = vertcat(rows{:});
end

function summary = local_horizon_summary(horizon_scores)
%LOCAL_HORIZON_SUMMARY Summarize pointwise scores by model, strategy, and lead.
keys = {'Model', 'ExoMode', 'Strategy', 'LeadTime'};
identities = unique(horizon_scores(:, keys), 'rows', 'stable');
rows = cell(height(identities), 1);

for group_index = 1:height(identities)
    identity = identities(group_index, :);
    mask = local_identity_mask(horizon_scores, identity, keys);
    group = horizon_scores(mask, :);
    rows{group_index} = table( ...
        identity.Model, identity.ExoMode, identity.Strategy, ...
        identity.LeadTime, height(group), mean(group.WIS), ...
        median(group.WIS), mean(group.AbsoluteError), ...
        mean(group.SquaredError), sqrt(mean(group.SquaredError)), ...
        mean(group.Error), mean(group.MeanCoverage), ...
        mean(group.MeanIntervalWidth), ...
        'VariableNames', { ...
        'Model', 'ExoMode', 'Strategy', 'LeadTime', 'NumForecasts', ...
        'MeanWIS', 'MedianWIS', 'MeanAbsoluteError', ...
        'MeanSquaredError', 'RMSE', 'MeanError', 'MeanCoverage', ...
        'MeanIntervalWidth'});
end

summary = vertcat(rows{:});
end

function summary = local_interval_summary(pointwise)
%LOCAL_INTERVAL_SUMMARY Summarize raw coverage indicators by interval level.
keys = {'Model', 'ExoMode', 'Strategy', 'Alpha', 'NominalCoverage'};
identities = unique(pointwise(:, keys), 'rows', 'stable');
rows = cell(height(identities), 1);

for group_index = 1:height(identities)
    identity = identities(group_index, :);
    mask = local_identity_mask(pointwise, identity, keys);
    group = pointwise(mask, :);
    empirical_coverage = mean(group.Coverage);
    rows{group_index} = table( ...
        identity.Model, identity.ExoMode, identity.Strategy, ...
        identity.Alpha, identity.NominalCoverage, height(group), ...
        empirical_coverage, ...
        empirical_coverage - identity.NominalCoverage, ...
        mean(group.IntervalWidth), ...
        'VariableNames', { ...
        'Model', 'ExoMode', 'Strategy', 'Alpha', 'NominalCoverage', ...
        'NumIntervalForecasts', 'EmpiricalCoverage', ...
        'CoverageError', 'MeanIntervalWidth'});
end

summary = vertcat(rows{:});
end

function mask = local_identity_mask(data, identity, keys)
%LOCAL_IDENTITY_MASK Match table rows to one grouping identity.
mask = true(height(data), 1);
for key_index = 1:numel(keys)
    key = keys{key_index};
    mask = mask & data.(key) == identity.(key);
end
end

function comparisons = local_pairwise_comparisons(origin_scores, cfg)
%LOCAL_PAIRWISE_COMPARISONS Build the seven planned matched comparisons.
rows = cell(7, 1);
row_index = 0;
strategies = cfg.evaluation.required_strategy_identifiers;

for strategy_index = 1:numel(strategies)
    strategy = strategies(strategy_index);
    row_index = row_index + 1;
    left = origin_scores( ...
        origin_scores.Model == "ARX" & ...
        origin_scores.ExoMode == "I" & ...
        origin_scores.Strategy == strategy, :);
    right = origin_scores( ...
        origin_scores.Model == "AR" & ...
        origin_scores.ExoMode == "None" & ...
        origin_scores.Strategy == strategy, :);
    rows{row_index} = local_matched_comparison( ...
        left, right, "model_within_strategy", strategy, ...
        "ARX/I", "AR/None", "ARX/I minus AR/None", cfg);
end

models = ["AR", "None"; "ARX", "I"];
for model_index = 1:size(models, 1)
    model = models(model_index, 1);
    exo_mode = models(model_index, 2);
    model_label = model + "/" + exo_mode;
    model_rows = origin_scores( ...
        origin_scores.Model == model & ...
        origin_scores.ExoMode == exo_mode, :);

    row_index = row_index + 1;
    rows{row_index} = local_matched_comparison( ...
        model_rows(model_rows.Strategy == "partA_fixed_fit", :), ...
        model_rows(model_rows.Strategy == "partA_online_fit", :), ...
        "fixed_vs_online_within_model", model_label, ...
        "partA_fixed_fit", "partA_online_fit", ...
        "partA_fixed_fit minus partA_online_fit", cfg);

    row_index = row_index + 1;
    rows{row_index} = local_matched_comparison( ...
        model_rows(model_rows.Strategy == "local_online_fit", :), ...
        model_rows(model_rows.Strategy == "partA_online_fit", :), ...
        "local_vs_partA_online_within_model", model_label, ...
        "local_online_fit", "partA_online_fit", ...
        "local_online_fit minus partA_online_fit", cfg);
end

comparisons = vertcat(rows{:});
end

function row = local_matched_comparison( ...
        left, right, comparison_type, context, left_label, ...
        right_label, definition, cfg)
%LOCAL_MATCHED_COMPARISON Compare WIS after exact origin matching.
left = sortrows(left, {'OriginIndex', 'OriginDate'});
right = sortrows(right, {'OriginIndex', 'OriginDate'});
matched = height(left) == 22 && height(right) == 22 && ...
    isequal(left.OriginIndex, right.OriginIndex) && ...
    isequal(left.OriginDate, right.OriginDate);

if ~matched
    error('PARTC_04:UnmatchedPairwiseOrigins', ...
        'Comparison %s does not contain exactly 22 common origins.', ...
        definition);
end

differences = left.MeanWIS - right.MeanWIS;
tolerance = cfg.evaluation.wis_equality_tolerance;
left_better = differences < -tolerance;
equal = abs(differences) <= tolerance;
right_better = differences > tolerance;

row = table( ...
    comparison_type, context, left_label, right_label, definition, ...
    numel(differences), mean(differences), median(differences), ...
    min(differences), max(differences), mean(left_better), ...
    mean(equal), mean(right_better), ...
    'VariableNames', { ...
    'ComparisonType', 'ModelOrStrategy', 'LeftLabel', 'RightLabel', ...
    'DifferenceDefinition', 'NumMatchedOrigins', 'MeanWISDifference', ...
    'MedianWISDifference', 'MinWISDifference', 'MaxWISDifference', ...
    'ProportionLeftBetter', 'ProportionEqual', ...
    'ProportionRightBetter'});
end

function equivalence = local_online_equivalence(artifacts, cfg)
%LOCAL_ONLINE_EQUIVALENCE Compare retained online strategies by model.
rows = cell(2, 1);

for pair_index = 1:2
    base_index = (pair_index - 1) * 3;
    partA_online = artifacts{base_index + 1};
    local_online = artifacts{base_index + 2};
    configurations_equal = isequal( ...
        partA_online.forecast_configuration, ...
        local_online.forecast_configuration);

    partA_median = vertcat(partA_online.results.forecast_median);
    local_median = vertcat(local_online.results.forecast_median);
    partA_lower = vertcat(partA_online.results.forecast_lower);
    local_lower = vertcat(local_online.results.forecast_lower);
    partA_upper = vertcat(partA_online.results.forecast_upper);
    local_upper = vertcat(local_online.results.forecast_upper);
    partA_targets = vertcat(partA_online.results.target_Rt_estimated);
    local_targets = vertcat(local_online.results.target_Rt_estimated);

    forecasts_identical = isequal(partA_median, local_median) && ...
        isequal(partA_lower, local_lower) && ...
        isequal(partA_upper, local_upper);
    targets_identical = isequal(partA_targets, local_targets);

    if configurations_equal && ~forecasts_identical
        error('PARTC_04:OnlineEquivalenceFailure', ...
            'Equal online configurations produced different forecasts for %s/%s.', ...
            partA_online.model_type, partA_online.exo_mode);
    end

    if configurations_equal
        interpretation = ...
            "The local configuration matched the Part A configuration, so local selection did not alter this model's held-out online forecasts.";
    else
        interpretation = ...
            "The local configuration differed from the Part A configuration, so exact online forecast equivalence was not required.";
    end

    rows{pair_index} = table( ...
        string(partA_online.model_type), string(partA_online.exo_mode), ...
        string(mat2str(partA_online.forecast_configuration)), ...
        string(mat2str(local_online.forecast_configuration)), ...
        configurations_equal, forecasts_identical, ...
        max(abs(partA_median - local_median), [], 'all'), ...
        max(abs(partA_lower - local_lower), [], 'all'), ...
        max(abs(partA_upper - local_upper), [], 'all'), ...
        targets_identical, interpretation, ...
        'VariableNames', { ...
        'Model', 'ExoMode', 'PartAConfiguration', 'LocalConfiguration', ...
        'ConfigurationsEqual', 'ForecastsExactlyIdentical', ...
        'MaxMedianAbsoluteDifference', 'MaxLowerAbsoluteDifference', ...
        'MaxUpperAbsoluteDifference', 'TargetsExactlyIdentical', ...
        'Interpretation'});
end

equivalence = vertcat(rows{:});

if any(equivalence.ConfigurationsEqual & ...
        ~equivalence.ForecastsExactlyIdentical)
    error('PARTC_04:OnlineEquivalenceFailure', ...
        'At least one equal online configuration failed exact equivalence.');
end

if ~all(equivalence.TargetsExactlyIdentical) || ...
        ~isequal(equivalence.Model, ["AR"; "ARX"]) || ...
        ~isequal(equivalence.ExoMode, ["None"; "I"]) || ...
        cfg.evaluation.wis_equality_tolerance < 0
    error('PARTC_04:InvalidOnlineEquivalence', ...
        'Online-equivalence results do not satisfy the required model and target contract.');
end
end

function local_validate_evaluation_results( ...
        origin_scores, horizon_scores, interval_scores, pointwise, ...
        summaries, comparisons, equivalence, artifacts, cfg)
%LOCAL_VALIDATE_EVALUATION_RESULTS Validate all detailed and grouped tables.
origin_variables = { ...
    'Model', 'ExoMode', 'Strategy', 'StrategyDescription', ...
    'ConfigurationSource', 'ParameterUpdateMode', ...
    'ForecastConfiguration', 'OriginPosition', 'OriginIndex', ...
    'OriginDate', 'TargetStartDate', 'TargetEndDate', 'MeanWIS', ...
    'RMSE', 'MAE', 'MeanError', 'MeanCoverage', ...
    'MeanIntervalWidth', 'FitAICc'};
horizon_variables = { ...
    'Model', 'ExoMode', 'Strategy', 'ForecastConfiguration', ...
    'OriginPosition', 'OriginIndex', 'OriginDate', 'LeadTime', ...
    'TargetIndex', 'TargetDate', 'TargetRtEstimated', ...
    'MedianForecast', 'Error', 'AbsoluteError', 'SquaredError', ...
    'WIS', 'MeanCoverage', 'MeanIntervalWidth'};
interval_variables = { ...
    'Model', 'ExoMode', 'Strategy', 'ForecastConfiguration', ...
    'OriginPosition', 'OriginDate', 'Alpha', 'NominalCoverage', ...
    'EmpiricalCoverage', 'CoverageError', 'MeanIntervalWidth'};

local_require_table_contract(origin_scores, origin_variables, 132, ...
    'origin_scores');
local_require_table_contract(horizon_scores, horizon_variables, 1848, ...
    'horizon_scores');
local_require_table_contract(interval_scores, interval_variables, ...
    6 * 22 * numel(artifacts{1}.wis_alphas), 'interval_scores');

numeric_scores = { ...
    origin_scores.MeanWIS
    origin_scores.RMSE
    origin_scores.MAE
    origin_scores.MeanError
    origin_scores.MeanCoverage
    origin_scores.MeanIntervalWidth
    origin_scores.FitAICc
    horizon_scores.TargetRtEstimated
    horizon_scores.MedianForecast
    horizon_scores.Error
    horizon_scores.AbsoluteError
    horizon_scores.SquaredError
    horizon_scores.WIS
    horizon_scores.MeanCoverage
    horizon_scores.MeanIntervalWidth
    interval_scores.EmpiricalCoverage
    interval_scores.CoverageError
    interval_scores.MeanIntervalWidth
    };

if any(cellfun(@(values) any(~isfinite(values)), numeric_scores))
    error('PARTC_04:NonfiniteEvaluationScore', ...
        'Every required target, forecast, score, and diagnostic must be finite.');
end

coverage_valid = all(origin_scores.MeanCoverage >= 0 & ...
    origin_scores.MeanCoverage <= 1) && ...
    all(horizon_scores.MeanCoverage >= 0 & ...
    horizon_scores.MeanCoverage <= 1) && ...
    all(interval_scores.EmpiricalCoverage >= 0 & ...
    interval_scores.EmpiricalCoverage <= 1) && ...
    all(pointwise.Coverage >= 0 & pointwise.Coverage <= 1);
width_valid = all(origin_scores.MeanIntervalWidth >= 0) && ...
    all(horizon_scores.MeanIntervalWidth >= 0) && ...
    all(interval_scores.MeanIntervalWidth >= 0) && ...
    all(isfinite(pointwise.IntervalWidth)) && ...
    all(pointwise.IntervalWidth >= 0);

if ~coverage_valid || ~width_valid
    error('PARTC_04:InvalidIntervalDiagnostics', ...
        'Coverage must lie in [0,1] and interval widths must be finite and nonnegative.');
end

local_validate_detailed_grids( ...
    origin_scores, horizon_scores, interval_scores, artifacts, cfg);
local_validate_summary_tables( ...
    origin_scores, horizon_scores, pointwise, summaries, cfg);

if height(comparisons) ~= 7 || ...
        any(comparisons.NumMatchedOrigins ~= 22) || ...
        any(abs(comparisons.ProportionLeftBetter + ...
        comparisons.ProportionEqual + ...
        comparisons.ProportionRightBetter - 1) > eps)
    error('PARTC_04:InvalidPairwiseComparisons', ...
        'Pairwise comparisons must contain seven complete matched-origin rows.');
end

if height(equivalence) ~= 2 || ...
        ~all(equivalence.ConfigurationsEqual) || ...
        ~all(equivalence.ForecastsExactlyIdentical) || ...
        ~all(equivalence.TargetsExactlyIdentical)
    error('PARTC_04:OnlineEquivalenceFailure', ...
        'The current equal online configurations must remain exactly equivalent.');
end
end

function local_require_table_contract(table_data, variables, row_count, name)
%LOCAL_REQUIRE_TABLE_CONTRACT Require exact columns and row count.
if ~istable(table_data) || ...
        ~isequal(table_data.Properties.VariableNames, variables) || ...
        height(table_data) ~= row_count
    error('PARTC_04:InvalidTableContract', ...
        '%s does not satisfy its required variable and row-count contract.', ...
        name);
end
end

function local_validate_detailed_grids( ...
        origin_scores, horizon_scores, interval_scores, artifacts, cfg)
%LOCAL_VALIDATE_DETAILED_GRIDS Reconcile identities, origins, targets, and alphas.
expected_models = ["AR"; "AR"; "AR"; "ARX"; "ARX"; "ARX"];
expected_exo_modes = ["None"; "None"; "None"; "I"; "I"; "I"];
expected_strategies = [ ...
    "partA_online_fit"
    "local_online_fit"
    "partA_fixed_fit"
    "partA_online_fit"
    "local_online_fit"
    "partA_fixed_fit"];
identities = unique( ...
    origin_scores(:, {'Model', 'ExoMode', 'Strategy'}), ...
    'rows', 'stable');

if ~isequal(identities.Model, expected_models) || ...
        ~isequal(identities.ExoMode, expected_exo_modes) || ...
        ~isequal(identities.Strategy, expected_strategies)
    error('PARTC_04:StrategyCoverageMismatch', ...
        'Detailed tables must retain all six model and strategy identities.');
end

for artifact_index = 1:numel(artifacts)
    artifact = artifacts{artifact_index};
    mask = origin_scores.Model == string(artifact.model_type) & ...
        origin_scores.ExoMode == string(artifact.exo_mode) & ...
        origin_scores.Strategy == string(artifact.strategy);
    origin_group = sortrows(origin_scores(mask, :), 'OriginPosition');
    horizon_mask = horizon_scores.Model == string(artifact.model_type) & ...
        horizon_scores.ExoMode == string(artifact.exo_mode) & ...
        horizon_scores.Strategy == string(artifact.strategy);
    horizon_group = sortrows( ...
        horizon_scores(horizon_mask, :), {'OriginPosition', 'LeadTime'});

    expected_origin_indices = [artifact.results.origin_index].';
    expected_origin_dates = [artifact.results.origin_date].';
    expected_target_indices = vertcat(artifact.results.target_indices);
    expected_target_dates = vertcat(artifact.results.target_dates);
    expected_targets = vertcat(artifact.results.target_Rt_estimated);

    valid = height(origin_group) == 22 && ...
        height(horizon_group) == 22 * cfg.final_forecast.horizon && ...
        isequal(origin_group.OriginIndex, expected_origin_indices) && ...
        isequal(origin_group.OriginDate, expected_origin_dates) && ...
        isequal(horizon_group.TargetIndex, expected_target_indices) && ...
        isequal(horizon_group.TargetDate, expected_target_dates) && ...
        isequal(horizon_group.TargetRtEstimated, expected_targets) && ...
        all(horizon_group.LeadTime == repmat( ...
        (1:cfg.final_forecast.horizon).', 22, 1));
    if ~valid
        error('PARTC_04:DetailedGridMismatch', ...
            'Detailed score rows do not reconcile with %s/%s/%s.', ...
            artifact.model_type, artifact.exo_mode, artifact.strategy);
    end
end

expected_alphas = artifacts{1}.wis_alphas;
if ~isequal(unique(interval_scores.Alpha, 'stable'), expected_alphas) || ...
        ~isequal(unique(interval_scores.NominalCoverage, 'stable'), ...
        1 - expected_alphas) || ...
        min(horizon_scores.TargetDate) < datetime(2021, 1, 1) || ...
        max(horizon_scores.TargetDate) > datetime(2021, 6, 10)
    error('PARTC_04:IntervalOrDateGridMismatch', ...
        'Detailed score tables contain incompatible alpha or target-date grids.');
end
end

function local_validate_summary_tables( ...
        origin_scores, horizon_scores, pointwise, summaries, cfg)
%LOCAL_VALIDATE_SUMMARY_TABLES Reconcile grouped summaries with raw rows.
if height(summaries.strategy_summary) ~= 6 || ...
        any(summaries.strategy_summary.NumOrigins ~= 22) || ...
        height(summaries.horizon_summary) ~= ...
        6 * cfg.final_forecast.horizon || ...
        any(summaries.horizon_summary.NumForecasts ~= 22) || ...
        height(summaries.interval_summary) ~= ...
        6 * numel(cfg.final_forecast.wis_alphas) || ...
        any(summaries.interval_summary.NumIntervalForecasts ~= ...
        22 * cfg.final_forecast.horizon)
    error('PARTC_04:SummaryCountMismatch', ...
        'Summary counts do not reconcile with the detailed evaluation rows.');
end

recomputed_strategy = local_strategy_summary(origin_scores);
recomputed_horizon = local_horizon_summary(horizon_scores);
recomputed_interval = local_interval_summary(pointwise);
if ~isequaln(summaries.strategy_summary, recomputed_strategy) || ...
        ~isequaln(summaries.horizon_summary, recomputed_horizon) || ...
        ~isequaln(summaries.interval_summary, recomputed_interval)
    error('PARTC_04:SummaryValueMismatch', ...
        'Grouped summaries are inconsistent with the detailed score rows.');
end
end

function local_commit_outputs( ...
        payload, mat_path, csv_tables, csv_paths, artifacts, pointwise, cfg)
%LOCAL_COMMIT_OUTPUTS Validate staged outputs and promote with rollback.
if exist(cfg.output.evaluation_dir, 'dir') ~= 7
    mkdir(cfg.output.evaluation_dir);
end
if exist(cfg.output.table_dir, 'dir') ~= 7
    mkdir(cfg.output.table_dir);
end

num_csv = numel(csv_paths);
canonical_paths = [string(mat_path); csv_paths];
staged_paths = strings(num_csv + 1, 1);
backup_paths = strings(num_csv + 1, 1);
had_canonical = false(num_csv + 1, 1);
promoted = false(num_csv + 1, 1);

try
    staged_paths(1) = string(tempname(cfg.output.evaluation_dir)) + ".mat";
    save(staged_paths(1), '-struct', 'payload');
    reloaded_payload = load(staged_paths(1));
    local_validate_reloaded_payload( ...
        reloaded_payload, payload, artifacts, pointwise, cfg);

    for csv_index = 1:num_csv
        staged_paths(csv_index + 1) = ...
            string(tempname(cfg.output.table_dir)) + ".csv";
        writetable(csv_tables{csv_index}, staged_paths(csv_index + 1), ...
            'QuoteStrings', true);
        reloaded_table = local_read_staged_csv( ...
            staged_paths(csv_index + 1), csv_tables{csv_index});
        local_validate_reloaded_csv( ...
            reloaded_table, csv_tables{csv_index}, csv_paths(csv_index), ...
            cfg.evaluation.wis_equality_tolerance);
    end
catch staging_error
    local_delete_paths(staged_paths);
    rethrow(staging_error);
end

try
    for output_index = 1:numel(canonical_paths)
        if exist(canonical_paths(output_index), 'file') == 2
            had_canonical(output_index) = true;
            [backup_directory, ~, extension] = ...
                fileparts(canonical_paths(output_index));
            backup_paths(output_index) = ...
                string(tempname(backup_directory)) + string(extension);
            [copied, message] = copyfile( ...
                canonical_paths(output_index), backup_paths(output_index));
            if ~copied
                error('PARTC_04:OutputBackupFailed', ...
                    'Could not back up %s: %s', ...
                    canonical_paths(output_index), message);
            end
        end
    end

    for output_index = 1:numel(canonical_paths)
        [moved, message] = movefile( ...
            staged_paths(output_index), canonical_paths(output_index), 'f');
        if ~moved
            error('PARTC_04:OutputPromotionFailed', ...
                'Could not promote %s: %s', ...
                canonical_paths(output_index), message);
        end
        promoted(output_index) = true;
        staged_paths(output_index) = "";
    end

    if any(arrayfun(@(path) exist(path, 'file') ~= 2, canonical_paths))
        error('PARTC_04:IncompleteCanonicalOutputSet', ...
            'The canonical evaluation output set is incomplete after promotion.');
    end
catch promotion_error
    rollback_failures = strings(numel(canonical_paths), 1);
    rollback_failure_count = 0;
    for output_index = 1:numel(canonical_paths)
        if ~promoted(output_index)
            continue
        end

        if had_canonical(output_index)
            [restored, message] = copyfile( ...
                backup_paths(output_index), canonical_paths(output_index), 'f');
            if ~restored
                rollback_failure_count = rollback_failure_count + 1;
                rollback_failures(rollback_failure_count) = ...
                    canonical_paths(output_index) + ": " + string(message);
            end
        elseif exist(canonical_paths(output_index), 'file') == 2
            delete(canonical_paths(output_index));
        end
    end

    rollback_failures = rollback_failures(1:rollback_failure_count);
    if rollback_failure_count == 0
        local_delete_paths(backup_paths);
    else
        warning('PARTC_04:RollbackIncomplete', ...
            'Rollback was incomplete; recovery backups were retained. %s', ...
            strjoin(rollback_failures, ' | '));
    end
    local_delete_paths(staged_paths);
    rethrow(promotion_error);
end

local_delete_paths(backup_paths);
end

function local_validate_reloaded_payload( ...
        reloaded, payload, artifacts, pointwise, cfg)
%LOCAL_VALIDATE_RELOADED_PAYLOAD Validate staged MAT round-trip integrity.
expected_fields = { ...
    'origin_scores'
    'horizon_scores'
    'interval_scores'
    'summaries'
    'pairwise_comparisons'
    'online_equivalence'
    'forecast_artifact_paths'
    'prepared_artifact_path'
    'preparation_snapshot'
    'forecast_snapshot'
    'evaluation_snapshot'
    'target_description'
    };

if ~isequal(fieldnames(reloaded), expected_fields) || ...
        ~isequaln(reloaded, payload)
    error('PARTC_04:StagedMatMismatch', ...
        'The staged evaluation MAT artifact failed exact round-trip validation.');
end

local_validate_evaluation_results( ...
    reloaded.origin_scores, reloaded.horizon_scores, ...
    reloaded.interval_scores, pointwise, ...
    reloaded.summaries, reloaded.pairwise_comparisons, ...
    reloaded.online_equivalence, artifacts, cfg);
end

function reloaded = local_read_staged_csv(path, source)
%LOCAL_READ_STAGED_CSV Read a staged CSV using its source table types.
variable_names = source.Properties.VariableNames;
variable_types = strings(1, width(source));
datetime_variables = strings(width(source), 1);
datetime_variable_count = 0;

for variable_index = 1:numel(variable_names)
    variable_name = variable_names{variable_index};
    source_values = source.(variable_name);
    if isdatetime(source_values)
        variable_types(variable_index) = "datetime";
        datetime_variable_count = datetime_variable_count + 1;
        datetime_variables(datetime_variable_count) = string(variable_name);
    elseif isstring(source_values)
        variable_types(variable_index) = "string";
    elseif islogical(source_values)
        variable_types(variable_index) = "logical";
    elseif isnumeric(source_values)
        variable_types(variable_index) = "double";
    else
        error('PARTC_04:UnsupportedCsvVariableType', ...
            'Unsupported staged CSV variable type for %s.', variable_name);
    end
end
datetime_variables = datetime_variables(1:datetime_variable_count);

options = delimitedTextImportOptions('NumVariables', width(source));
options.DataLines = [2, Inf];
options.Delimiter = ',';
options.VariableNames = variable_names;
options.VariableTypes = variable_types;
options.VariableNamingRule = 'preserve';

for datetime_index = 1:numel(datetime_variables)
    variable_name = datetime_variables(datetime_index);
    options = setvaropts(options, variable_name, 'InputFormat', ...
        source.(variable_name).Format);
end

reloaded = readtable(path, options);

if width(reloaded) ~= width(source)
    error('PARTC_04:StagedCsvImportFailure', ...
        'Staged CSV did not reload with the expected number of variables: %s.', ...
        path);
end
end

function local_validate_reloaded_csv( ...
        reloaded, source, canonical_path, numeric_tolerance)
%LOCAL_VALIDATE_RELOADED_CSV Validate staged CSV schema and values.
if ~isequal(reloaded.Properties.VariableNames, ...
        source.Properties.VariableNames) || height(reloaded) ~= height(source)
    error('PARTC_04:StagedCsvContractMismatch', ...
        'Staged CSV failed its schema or row-count contract: %s.', ...
        canonical_path);
end

variable_names = source.Properties.VariableNames;
for variable_index = 1:numel(variable_names)
    variable_name = variable_names{variable_index};
    source_values = source.(variable_name);
    reloaded_values = reloaded.(variable_name);

    if isnumeric(source_values)
        if ~isnumeric(reloaded_values)
            reloaded_values = str2double(string(reloaded_values));
        end
        exact_numeric_variables = { ...
            'OriginPosition', 'OriginIndex', 'LeadTime', 'TargetIndex', ...
            'NumOrigins', 'NumForecasts', 'NumIntervalForecasts', ...
            'NumMatchedOrigins', 'Alpha', 'NominalCoverage'};
        if ismember(variable_name, exact_numeric_variables)
            values_match = isequal(reloaded_values, source_values);
        else
            round_trip_tolerance = numeric_tolerance * ...
                max(1, abs(source_values));
            values_match = ...
                isequal(size(reloaded_values), size(source_values)) && ...
                all(abs(reloaded_values - source_values) <= ...
                round_trip_tolerance, 'all');
        end
    elseif islogical(source_values)
        values_match = isequal( ...
            lower(string(reloaded_values)), lower(string(source_values)));
    elseif isdatetime(source_values)
        values_match = isequal( ...
            string(reloaded_values), string(source_values));
    else
        values_match = isequal(string(reloaded_values), string(source_values));
    end

    if ~values_match
        error('PARTC_04:StagedCsvValueMismatch', ...
            'Staged CSV changed variable %s in %s.', ...
            variable_name, canonical_path);
    end
end
end

function local_delete_paths(paths)
%LOCAL_DELETE_PATHS Delete existing transaction files.
for path_index = 1:numel(paths)
    if strlength(paths(path_index)) > 0 && ...
            exist(paths(path_index), 'file') == 2
        delete(paths(path_index));
    end
end
end
