%PARTA_04_EVALUATE_MODELS Comparative Evaluation of Epidemic Forecasts
%
%   Description:
%       Aggregates and scores the performance of all forecasting models
%       generated by the unified forecast pipeline. Calculates the
%       Weighted Interval Score (WIS) for every expanding window,
%       producing summary statistics and comparative visualizations.
%
%   Workflow:
%       1. Identify all forecast artifacts in the output directory.
%       2. Parse filenames to extract Model Type, Exogenous Mode, and Scenario.
%       3. Compute WIS for every forecast window.
%       4. Aggregate statistics to identify the optimal model configuration.
%       5. Generate comparative boxplots via a dedicated plotting function.
%
%   See also PARTA_CONFIG, PLOT_MODEL_PERFORMANCE.

% A. M. Kaahin 2026-02-19
% Modified: 2026-03-28

%% 1. Initialization
clear; close all; clc;

fprintf('=== Model Evaluation ===\n');

cfg = partA_config();
forecastDir = cfg.output.forecast_dir;
scoreDir    = cfg.output.score_dir;
figDir      = cfg.output.fig_dir;

if ~exist(scoreDir, 'dir'), mkdir(scoreDir); end
if ~exist(figDir, 'dir'),   mkdir(figDir); end

fprintf('Scanning forecast directory: %s\n', forecastDir);

filePattern = fullfile(forecastDir, 'partA_02_forecast_*.mat');
files       = dir(filePattern);

if isempty(files)
    error('EVAL:NoData', 'No forecast results found. Run partA_03_run_forecasts.m first.');
end

%% 2. Score Aggregation
score_registry    = table();
pointwise_details = table();
score_blocks      = cell(length(files), 1);
detail_blocks     = cell(length(files), 1);
valid_models      = {'AR', 'ARX', 'N4SID', 'SSEST'};

for i = 1:length(files)
    filename = files(i).name;
    fullPath = fullfile(forecastDir, filename);
    
    [~, nameBody] = fileparts(filename);
    tokens = split(nameBody, '_');
    
    if length(tokens) >= 6
        scenario_id = tokens{4};
        model_type  = tokens{5};
        exo_mode    = tokens{6};
    else
        continue;
    end

    if ~any(strcmp(model_type, valid_models))
        continue;
    end
    
    data = load(fullPath);
    if ~isfield(data, 'results') || isempty(data.results)
        continue;
    end
    results = data.results;

    if ~all(isfield(results, {'forecast_median', 'forecast_interval_alphas', 'forecast_lower', 'forecast_upper'}))
        continue;
    end

    file_score_blocks  = cell(length(results), 1);
    file_detail_blocks = cell(length(results), 1);
    
    for k = 1:length(results)
        truth_Rt = double(results(k).truth_Rt_window(:));
        pred_Rt  = double(results(k).forecast_median(:));
        alphas   = reshape(double(results(k).forecast_interval_alphas), 1, []);
        lower_Rt = double(results(k).forecast_lower);
        upper_Rt = double(results(k).forecast_upper);

        if numel(truth_Rt) ~= numel(pred_Rt)
            continue;
        end

        if size(lower_Rt, 1) ~= numel(truth_Rt) || size(upper_Rt, 1) ~= numel(truth_Rt)
            continue;
        end

        if size(lower_Rt, 2) ~= numel(alphas) || size(upper_Rt, 2) ~= numel(alphas)
            continue;
        end

        pointwise_wis = compute_wis(truth_Rt, pred_Rt, lower_Rt, upper_Rt, alphas);
        if any(~isfinite(pointwise_wis))
            continue;
        end

        window_wis = mean(pointwise_wis);

        file_score_blocks{k} = table( ...
            categorical(string(scenario_id)), ...
            categorical(string(model_type)), ...
            categorical(string(exo_mode)), ...
            results(k).window_day, ...
            window_wis);

        horizon_idx = (1:numel(truth_Rt))';
        file_detail_blocks{k} = table( ...
            repmat(categorical(string(scenario_id)), numel(truth_Rt), 1), ...
            repmat(categorical(string(model_type)), numel(truth_Rt), 1), ...
            repmat(categorical(string(exo_mode)), numel(truth_Rt), 1), ...
            repmat(results(k).window_day, numel(truth_Rt), 1), ...
            horizon_idx, ...
            double(results(k).time_horizon(:)), ...
            truth_Rt, ...
            pred_Rt, ...
            pointwise_wis);
    end

    file_score_blocks = file_score_blocks(~cellfun('isempty', file_score_blocks));
    if ~isempty(file_score_blocks)
        score_blocks{i} = vertcat(file_score_blocks{:});
    end

    file_detail_blocks = file_detail_blocks(~cellfun('isempty', file_detail_blocks));
    if ~isempty(file_detail_blocks)
        detail_blocks{i} = vertcat(file_detail_blocks{:});
    end
end

score_blocks = score_blocks(~cellfun('isempty', score_blocks));
if ~isempty(score_blocks)
    score_registry = vertcat(score_blocks{:});
end

detail_blocks = detail_blocks(~cellfun('isempty', detail_blocks));
if ~isempty(detail_blocks)
    pointwise_details = vertcat(detail_blocks{:});
end

if isempty(score_registry)
    error('EVAL:NoProbabilisticData', ...
        'No probabilistic forecast results found. Run partA_03_run_forecasts.m first.');
end

score_registry.Properties.VariableNames = {'Scenario', 'Model', 'ExoMode', 'WindowDay', 'WindowWIS'};
pointwise_details.Properties.VariableNames = { ...
    'Scenario', 'Model', 'ExoMode', 'WindowDay', 'HorizonIdx', ...
    'ForecastDay', 'Truth_Rt', 'Median_Forecast', 'WIS'};

fprintf('Aggregated scores for %d total forecast windows.\n', height(score_registry));

%% 3. Summary Statistics
summary_stats = groupsummary(score_registry, ...
    {'Scenario', 'Model', 'ExoMode'}, ...
    {'mean', 'median', 'std', 'min', 'max'}, ...
    'WindowWIS');

summary_stats.Properties.VariableNames = regexprep(summary_stats.Properties.VariableNames, ...
    {'mean_', 'median_', 'std_', 'min_', 'max_'}, ...
    {'Mean_', 'Median_', 'Std_', 'Min_', 'Max_'});

fprintf('\n  [ Performance Summary (WIS) ]\n');
disp(summary_stats(:, {'Scenario', 'Model', 'ExoMode', 'Mean_WindowWIS', 'Std_WindowWIS'}));

summaryFile = fullfile(scoreDir, 'partA_03_wis_performance_summary.csv');
writetable(summary_stats, summaryFile);
fprintf('Summary statistics saved to: %s\n', summaryFile);

detailFile = fullfile(scoreDir, 'partA_03_wis_pointwise_details.csv');
writetable(pointwise_details, detailFile);
fprintf('Pointwise WIS details saved to: %s\n', detailFile);

alpha_labels = string(strjoin(compose('%.2f', double(cfg.forecast.wis_alphas)), ', '));
settingsFile = fullfile(scoreDir, 'partA_03_wis_settings.csv');
writetable(table(alpha_labels, 'VariableNames', {'WIS_Alphas'}), settingsFile);
fprintf('WIS settings saved to: %s\n', settingsFile);

%% 4. Visualization
plot_model_performance(score_registry, cfg);

out_path = fullfile(cfg.output.fig_dir, 'partA_03_wis_performance_boxplot.png');
fprintf('Performance visualization saved to: %s\n', out_path);
fprintf('=== Evaluation Complete ===\n\n');

function wis = compute_wis(truth_Rt, median_Rt, lower_Rt, upper_Rt, alphas)
    num_intervals = numel(alphas);
    wis = 0.5 * abs(truth_Rt - median_Rt);

    for j = 1:num_intervals
        alpha = alphas(j);
        interval_score = (upper_Rt(:, j) - lower_Rt(:, j)) ...
            + (2 / alpha) * max(lower_Rt(:, j) - truth_Rt, 0) ...
            + (2 / alpha) * max(truth_Rt - upper_Rt(:, j), 0);
        wis = wis + (alpha / 2) * interval_score;
    end

    wis = wis / (num_intervals + 0.5);
end
