%PARTA_03_EVALUATE_MODELS Comparative Evaluation of Epidemic Forecasts
%
%   Description:
%       Aggregates and scores the performance of all forecasting models 
%       generated by the unified forecast pipeline. Calculates Root Mean 
%       Square Error (RMSE) for every expanding window, producing summary 
%       statistics and comparative visualizations.
%
%   Workflow:
%       1. Identify all forecast artifacts in the output directory.
%       2. Parse filenames to extract Model Type, Exogenous Mode, and Scenario.
%       3. Compute error metrics (RMSE) for every forecast window.
%       4. Aggregate statistics to identify the optimal model configuration.
%       5. Generate comparative boxplots via a dedicated plotting function.
%
%   See also PARTA_CONFIG, PLOT_MODEL_PERFORMANCE.

% A. M. Kaahin 2026-02-19

%% 1. Initialization
clear; close all; clc;

fprintf('=== Model Evaluation ===\n');

cfg = partA_config();
forecastDir = cfg.output.forecast_dir;
scoreDir    = cfg.output.score_dir;
figDir      = cfg.output.fig_dir;

if ~exist(scoreDir, 'dir'), mkdir(scoreDir); end
if ~exist(figDir, 'dir'),   mkdir(figDir); end

fprintf('Scanning forecast directory: %s\n', forecastDir);

filePattern = fullfile(forecastDir, 'partA_02_forecast_*.mat');
files       = dir(filePattern);

if isempty(files)
    error('EVAL:NoData', 'No forecast results found. Run partA_02_run_forecasts.m first.');
end

%% 2. Score Aggregation
score_registry = table();

for i = 1:length(files)
    filename = files(i).name;
    fullPath = fullfile(forecastDir, filename);
    
    [~, nameBody] = fileparts(filename);
    tokens = split(nameBody, '_');
    
    if length(tokens) >= 6
        scenario_id = tokens{4};
        model_type  = tokens{5};
        exo_mode    = tokens{6};
    else
        warning('EVAL:BadNaming', 'Skipping file with non-standard naming: %s', filename);
        continue;
    end
    
    data = load(fullPath);
    if ~isfield(data, 'results')
        warning('EVAL:Malformed', 'Skipping malformed file: %s', filename);
        continue;
    end
    results = data.results;
    
    for k = 1:length(results)
        pred_Rt  = double(results(k).forecast_Rt(:));
        truth_Rt = double(results(k).truth_Rt_window(:));
        
        residuals = pred_Rt - truth_Rt;
        rmse_val  = sqrt(mean(residuals.^2));
        
        newRow = { ...
            categorical(string(scenario_id)), ...
            categorical(string(model_type)), ...
            categorical(string(exo_mode)), ...
            results(k).window_day, ...
            rmse_val ...
        };
        
        score_registry = [score_registry; newRow]; 
    end
end

score_registry.Properties.VariableNames = {'Scenario', 'Model', 'ExoMode', 'WindowDay', 'RMSE'};

fprintf('Aggregated scores for %d total forecast windows.\n', height(score_registry));

%% 3. Summary Statistics
summary_stats = groupsummary(score_registry, ...
    {'Scenario', 'Model', 'ExoMode'}, ...
    {'mean', 'std', 'min', 'max'}, ...
    'RMSE');

summary_stats.Properties.VariableNames = regexprep(summary_stats.Properties.VariableNames, ...
    {'mean_', 'std_', 'min_', 'max_'}, {'Mean_', 'Std_', 'Min_', 'Max_'});

fprintf('\n  [ Performance Summary (RMSE) ]\n');
disp(summary_stats(:, {'Scenario', 'Model', 'ExoMode', 'Mean_RMSE', 'Std_RMSE'}));

summaryFile = fullfile(scoreDir, 'partA_03_model_performance_summary.csv');
writetable(summary_stats, summaryFile);
fprintf('Summary statistics saved to: %s\n', summaryFile);

%% 4. Visualization
plot_model_performance(score_registry, cfg);

out_path = fullfile(cfg.output.fig_dir, 'partA_03_performance_boxplot.png');
fprintf('Performance visualization saved to: %s\n', out_path);
fprintf('=== Evaluation Complete ===\n\n');