%PARTA_04_EVALUATE_FORECASTS Comparative evaluation of epidemic forecasts.
%
%   Description:
%       Aggregates and scores the performance of all forecasting models
%       generated by the unified forecast pipeline. Calculates the
%       Weighted Interval Score (WIS) for every expanding window,
%       penalizing invalid forecast windows with Inf to preserve
%       consistency with the tuning workflow.
%
%   Workflow:
%       1. Identify all forecast artifacts in the output directory.
%       2. Parse filenames to extract Model Type, Exogenous Mode, and Scenario.
%       3. Compute WIS for every forecast window.
%       4. Aggregate statistics to identify the optimal model configuration.
%       5. Generate comparative boxplots via a dedicated plotting function.
%
%   See also PARTA_CONFIG, PLOT_MODEL_PERFORMANCE, PARTA_03_RUN_FORECASTS.

% A. M. Kaahin 2026-02-19
% Modified: 2026-06-01

%% 1. Initialization
clear; close all; clc;

fprintf('=== Model Evaluation ===\n');

cfg = partA_config();
forecastDir = cfg.output.forecast_dir;
scoreDir    = cfg.output.score_dir;
figDir      = cfg.output.fig_dir;

if ~exist(scoreDir, 'dir'), mkdir(scoreDir); end
if ~exist(figDir, 'dir'),   mkdir(figDir); end

fprintf('Scanning forecast directory: %s\n', forecastDir);

filePattern = fullfile(forecastDir, 'partA_03_forecast_*.mat');
files       = dir(filePattern);

if isempty(files)
    error('EVAL:NoData', 'No forecast results found. Run partA_03_run_forecasts.m first.');
end

%% 2. Score Aggregation
score_registry    = table();
pointwise_details = table();
score_blocks      = cell(length(files), 1);
detail_blocks     = cell(length(files), 1);
valid_models      = {'AR', 'ARX', 'N4SID', 'SSEST'};

for i = 1:length(files)
    filename = files(i).name;
    fullPath = fullfile(forecastDir, filename);
    
    [~, nameBody] = fileparts(filename);
    tokens = split(nameBody, '_');
    
    if length(tokens) >= 6
        scenario_id = tokens{4};
        model_type  = tokens{5};
        exo_mode    = tokens{6};
    else
        continue;
    end

    if ~any(strcmp(model_type, valid_models))
        continue;
    end
    
    data = load(fullPath);
    if ~isfield(data, 'results') || isempty(data.results)
        continue;
    end
    results = data.results;

    if ~all(isfield(results, {'forecast_median', 'forecast_interval_alphas', 'forecast_lower', 'forecast_upper'}))
        continue;
    end

    file_score_blocks  = cell(length(results), 1);
    file_detail_blocks = cell(length(results), 1);
    
    for k = 1:length(results)
        [file_score_blocks{k}, file_detail_blocks{k}] = ...
            evaluate_window_result(results(k), scenario_id, model_type, exo_mode);
    end

    file_score_blocks = file_score_blocks(~cellfun('isempty', file_score_blocks));
    if ~isempty(file_score_blocks)
        score_blocks{i} = vertcat(file_score_blocks{:});
    end

    file_detail_blocks = file_detail_blocks(~cellfun('isempty', file_detail_blocks));
    if ~isempty(file_detail_blocks)
        detail_blocks{i} = vertcat(file_detail_blocks{:});
    end
end

score_blocks = score_blocks(~cellfun('isempty', score_blocks));
if ~isempty(score_blocks)
    score_registry = vertcat(score_blocks{:});
end

detail_blocks = detail_blocks(~cellfun('isempty', detail_blocks));
if ~isempty(detail_blocks)
    pointwise_details = vertcat(detail_blocks{:});
end

if isempty(score_registry)
    error('EVAL:NoProbabilisticData', ...
        'No probabilistic forecast results found. Run partA_03_run_forecasts.m first.');
end

score_registry.Properties.VariableNames = {'Scenario', 'Model', 'ExoMode', 'WindowDay', 'WindowWIS'};

if isempty(pointwise_details)
    pointwise_details = empty_pointwise_table();
else
    pointwise_details.Properties.VariableNames = { ...
        'Scenario', 'Model', 'ExoMode', 'WindowDay', 'HorizonIdx', ...
        'ForecastDay', 'Truth_Rt', 'Median_Forecast', 'WIS'};
end

fprintf('Aggregated scores for %d total forecast windows.\n', height(score_registry));

%% 3. Summary Statistics
summary_stats = groupsummary(score_registry, ...
    {'Scenario', 'Model', 'ExoMode'}, ...
    {'mean', 'median', 'std', 'min', 'max'}, ...
    'WindowWIS');

summary_stats.Properties.VariableNames = regexprep(summary_stats.Properties.VariableNames, ...
    {'mean_', 'median_', 'std_', 'min_', 'max_'}, ...
    {'Mean_', 'Median_', 'Std_', 'Min_', 'Max_'});

summary_stats = classify_wis_summary(summary_stats);
score_registry = attach_comparison_flags(score_registry, summary_stats);

fprintf('\n  [ Performance Summary (WIS) ]\n');
disp(summary_stats(:, {'Scenario', 'Model', 'ExoMode', 'Mean_WindowWIS', ...
    'Std_WindowWIS', 'IsAcceptable', 'FailureReason', 'IncludeInMainComparison'}));

summaryFile = fullfile(scoreDir, 'partA_04_wis_performance_summary.csv');
writetable(summary_stats, summaryFile);
fprintf('Summary statistics saved to: %s\n', summaryFile);

detailFile = fullfile(scoreDir, 'partA_04_wis_pointwise_details.csv');
writetable(pointwise_details, detailFile);
fprintf('Pointwise WIS details saved to: %s\n', detailFile);

alpha_labels = string(strjoin(compose('%.2f', double(cfg.forecast.wis_alphas)), ', '));
settingsFile = fullfile(scoreDir, 'partA_04_wis_settings.csv');
writetable(table(alpha_labels, 'VariableNames', {'WIS_Alphas'}), settingsFile);
fprintf('WIS settings saved to: %s\n', settingsFile);

%% 4. Visualization
plot_saved = plot_model_performance(score_registry, cfg);

out_path = fullfile(cfg.output.fig_dir, 'partA_04_wis_performance_boxplot.png');
if plot_saved
    fprintf('Performance visualization saved to: %s\n', out_path);
else
    fprintf('Performance visualization skipped: no finite WIS values were available.\n');
end
fprintf('=== Evaluation Complete ===\n\n');

%% 5. Local Functions
function [score_row, detail_rows] = evaluate_window_result(result_entry, scenario_id, model_type, exo_mode)
%EVALUATE_WINDOW_RESULT Compute WIS summaries for a single forecast window.
    truth_Rt = double(result_entry.truth_Rt_window(:));
    pred_Rt  = double(result_entry.forecast_median(:));
    alphas   = reshape(double(result_entry.forecast_interval_alphas), 1, []);
    lower_Rt = double(result_entry.forecast_lower);
    upper_Rt = double(result_entry.forecast_upper);

    window_wis = inf;
    detail_rows = empty_pointwise_table();

    is_valid_shape = ...
        numel(truth_Rt) == numel(pred_Rt) && ...
        size(lower_Rt, 1) == numel(truth_Rt) && ...
        size(upper_Rt, 1) == numel(truth_Rt) && ...
        size(lower_Rt, 2) == numel(alphas) && ...
        size(upper_Rt, 2) == numel(alphas) && ...
        ~isempty(alphas);

    if is_valid_shape
        pointwise_wis = compute_wis(truth_Rt, pred_Rt, lower_Rt, upper_Rt, alphas);
        if any(~isfinite(pointwise_wis))
            pointwise_wis = inf(numel(truth_Rt), 1);
        else
            window_wis = mean(pointwise_wis);
        end

        if numel(result_entry.time_horizon(:)) == numel(truth_Rt)
            horizon_idx = (1:numel(truth_Rt))';
            detail_rows = table( ...
                repmat(categorical(string(scenario_id)), numel(truth_Rt), 1), ...
                repmat(categorical(string(model_type)), numel(truth_Rt), 1), ...
                repmat(categorical(string(exo_mode)), numel(truth_Rt), 1), ...
                repmat(result_entry.window_day, numel(truth_Rt), 1), ...
                horizon_idx, ...
                double(result_entry.time_horizon(:)), ...
                truth_Rt, ...
                pred_Rt, ...
                pointwise_wis, ...
                'VariableNames', {'Scenario', 'Model', 'ExoMode', 'WindowDay', ...
                'HorizonIdx', 'ForecastDay', 'Truth_Rt', 'Median_Forecast', 'WIS'});
        end
    end

    score_row = table( ...
        categorical(string(scenario_id)), ...
        categorical(string(model_type)), ...
        categorical(string(exo_mode)), ...
        result_entry.window_day, ...
        window_wis);
end

function wis = compute_wis(truth_Rt, median_Rt, lower_Rt, upper_Rt, alphas)
%COMPUTE_WIS Compute pointwise weighted interval score values.
    num_intervals = numel(alphas);
    wis = 0.5 * abs(truth_Rt - median_Rt);

    for j = 1:num_intervals
        alpha = alphas(j);
        interval_score = (upper_Rt(:, j) - lower_Rt(:, j)) ...
            + (2 / alpha) * max(lower_Rt(:, j) - truth_Rt, 0) ...
            + (2 / alpha) * max(truth_Rt - upper_Rt(:, j), 0);
        wis = wis + (alpha / 2) * interval_score;
    end

    wis = wis / (num_intervals + 0.5);
end

function detail_rows = empty_pointwise_table()
%EMPTY_POINTWISE_TABLE Construct an empty pointwise WIS table.
    detail_rows = table( ...
        categorical.empty(0, 1), ...
        categorical.empty(0, 1), ...
        categorical.empty(0, 1), ...
        zeros(0, 1), ...
        zeros(0, 1), ...
        zeros(0, 1), ...
        zeros(0, 1), ...
        zeros(0, 1), ...
        zeros(0, 1), ...
        'VariableNames', {'Scenario', 'Model', 'ExoMode', 'WindowDay', ...
        'HorizonIdx', 'ForecastDay', 'Truth_Rt', 'Median_Forecast', 'WIS'});
end

function summary_stats = classify_wis_summary(summary_stats)
%CLASSIFY_WIS_SUMMARY Mark out-of-scale WIS scores before plotting/ranking.
    num_rows = height(summary_stats);
    mean_wis = summary_stats.Mean_WindowWIS;

    is_acceptable = true(num_rows, 1);
    failure_reason = strings(num_rows, 1);

    invalid_idx = ~isfinite(mean_wis) | mean_wis <= 0;
    is_acceptable(invalid_idx) = false;
    failure_reason(invalid_idx) = "nonfinite_or_nonpositive_wis";

    finite_positive_idx = isfinite(mean_wis) & mean_wis > 0;
    finite_positive_wis = mean_wis(finite_positive_idx);

    if numel(finite_positive_wis) >= 3
        log_wis = log10(finite_positive_wis);
        center_log_wis = median(log_wis);
        robust_spread = median(abs(log_wis - center_log_wis));
        outlier_threshold = center_log_wis + max(6 * robust_spread, 3);

        all_log_wis = nan(num_rows, 1);
        all_log_wis(finite_positive_idx) = log10(mean_wis(finite_positive_idx));
        outlier_idx = finite_positive_idx & all_log_wis > outlier_threshold;

        is_acceptable(outlier_idx) = false;
        failure_reason(outlier_idx) = "robust_log_outlier";
    end

    include_in_main = false(num_rows, 1);
    config_table = unique(summary_stats(:, {'Model', 'ExoMode'}), 'rows');

    for i = 1:height(config_table)
        config_idx = summary_stats.Model == config_table.Model(i) & ...
            summary_stats.ExoMode == config_table.ExoMode(i);
        include_in_main(config_idx) = all(is_acceptable(config_idx));
    end

    summary_stats.IsAcceptable = is_acceptable;
    summary_stats.FailureReason = failure_reason;
    summary_stats.IncludeInMainComparison = include_in_main;
end

function score_registry = attach_comparison_flags(score_registry, summary_stats)
%ATTACH_COMPARISON_FLAGS Propagate configuration-level plotting status.
    include_in_main = false(height(score_registry), 1);
    config_table = unique(summary_stats(:, {'Model', 'ExoMode', 'IncludeInMainComparison'}), 'rows');

    for i = 1:height(config_table)
        config_idx = score_registry.Model == config_table.Model(i) & ...
            score_registry.ExoMode == config_table.ExoMode(i);
        include_in_main(config_idx) = config_table.IncludeInMainComparison(i);
    end

    score_registry.IncludeInMainComparison = include_in_main;
end
